### ISSUE TITLE
Bug dev / install (1)

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#104]
Petit bug dans l'install.

`$GLOBALS['step'] = isset($_GET['s']) and is_numeric($_GET['s']) ? $_GET['s'] + 0 : 1;`

$GLOBALS['step'] retourne 0

alors que 
`$GLOBALS['step'] = (isset($_GET['s']) and is_numeric($_GET['s'])) ? $_GET['s'] + 0 : 1;`

$GLOBALS['step'] retourne 1

Mauvaise syntaxe sur la condition ternaire.

_Update :_ 
Apparemment, la plupart des conditions ternaires ont été modifiées `() ? : ;` pour ` ? : ;`, personnellement je trouve ça moins lisible et pose des problèmes en cas de multiples conditions (voir ci-dessus), de plus,  l'on risque de se retrouver avec deux syntaxes : 
`$v = ($a === true && $b === true) ? 'ok' : 'Nok' ;`
`$w = $a ===true ? 'ok' : 'Nok' ;`
`$x = $a === true;`
Je propose que l'on garde le test conditionnel entre `()` : 
`$v = ($a === true && $b === true) ? 'ok' : 'Nok' ;`
`$w = ($a === true) ? 'ok' : 'Nok' ;`
`$x = ($a === true);`

**Comment by BoboTiG** [comment]
Bien vu, j'ai déconné grave. J'ai modifié comme si c'était du Python...  Faudra que je m'en occupe rapidement. Si tu veux proposer un patch, dis-le moi,  histoire de ne pas faire deux fois les mêmes modifs.

Merci pour le rapport :)

**Comment by remrem** [comment]
je vais bosser sur blogotext ce soir, je peux reprendre et pousser un commit d'ici demain matin (je pense)...

**Comment by BoboTiG** [comment]
Excellent !
