### ISSUE TITLE
Ajouts de paramètres pour les addons

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#107]
J'avais déjà lancé le sujet - #70 - 
l'idée est de proposer aux développeurs d'addons de pouvoir mettre des paramètres modifiable via l'interface admin.

Les paramètres possibles et par défauts sont présentés dans le fichier .php de l'addon et les paramètres soumis par l'utilisateur sont enregistrés dans un fichier ini dans le répertoire de l'addon, ainsi, pas de requêtes SQL, en cas d'ajout/suppression de paramètre par le développeur lors de la mise à jour de son addon (array php), l'utilisateur ne perd pas sa config (ini).

**Comment by remrem** [comment]
au besoin, je publie un addon de démo demain

**Comment by remrem** [comment]
addon de démo https://github.com/BoboTiG/blogotext-addons/pull/4

**Comment by remrem** [comment]
Juste pour info, le fichier params.ini peut être effacé, il sera recréé automatiquement dès que l'utilisateur modifiera les paramètres du plugin.

**Comment by BoboTiG** [comment]
L'approche me semble très bien. Je merge dès qu'il n'y aura plus de conflit :)

**Comment by remrem** [comment]
PR #114 doit le faire

**Comment by BoboTiG** [comment]
Quelques retours : 
- quand on clique sur `params` : `Notice: Undefined variable: return in inc/modu.php on line 150` ;
- quand on clique sur `params` puis `Annuler`, on arrive dans les préférences au lieu des modules ;
- tranduire correctement `params` :)
- quand il y a une URL et des paramètres, ajouter un séparateur autre que l'espace ?

Et côté design, quand on est dans les params d'un addon, peut-être utiliser le même affichage que les prefs en mettant le nom de l'addon au dessus du cadre où sont gérés les paramètres, et ne pas afficher les infos de l'addon. Qu'en penses-tu ?

**Comment by remrem** [comment]
Je m'en occupe cet après-midi.

**Comment by remrem** [comment]
Point de vue template, je pensais rester raccord avec la présentation des modules afin de conserver le "header" des modules (bouton On/off)... Du coup ?

**Comment by BoboTiG** [comment]
J'me dis que vu qu'on est dans la page de configuration d'un module, c'est voulu. Du coup, une présentation des options avec le nom du module suffirait, je pense.

**Comment by remrem** [comment]
cf. #125 qui devrait répondre à tes retours.

J'ai pris la liberté d'ajouté un intitulé pour bien préciser que c'était les préférences/settings en plus du titre de l'addon, ça me semble un peu léger de juste mettre le titre de l'addon...

**Comment by BoboTiG** [comment]
Génial, merci ! Ça rend pas mal finalement, non ?

**Comment by remrem** [comment]
oui, seul truc que j'aurais aimé, c'est ce bouton pour activer/désactiver le plugin ;)
