### ISSUE TITLE
Virer travis et PSR2 ?

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#108]
Bon, j'aime bien blogotext, je m’accommode avec du mal de github (mais vu les avantages, je veux bien faire des efforts), mais PSR2 ... nan, désolé, too much pour moi. On ne peux pas virer le psr2 pour une convention plus légère ?

N.B. Loin de moi l'intention de lancer un débat ou partir dans du trollage de haut vol, juste une question qui ne demande qu'un "oui" ou un "non" ;)

**Comment by BoboTiG** [comment]
Je t'explique pourquoi j'y tiens et propose une solution plutôt simple ensuite.

Le projet attirant de plus en plus de monde (contributeurs comme toi et Thurban actuellement) et le dépôt des addons qui va lui aussi permettre à tout le monde de proposer toute sorte de module, j'ai l'intime conviction qu'il faille une base de code qui suive un standard, ici PSR-2. Comme pour tous les projets, chacun s'adapte à la norme en vigueur s'il souhaite proposer un patch. Même moi, ça m'oblige à revoir certaines choses car j'ai _mon style de codage_, toi tu as le tien et chaque personne a le sien ; il faut un moyen d'uniformiser tout ça.
Beaucoup de projets Python n'acceptent du code que s'il est conforme à la PEP8, par exemple.

Là, c'est un peu rude étant donné que tu es pile poil dans la transition, mais pour les futurs contributeurs, étant donné qu'il s'agit maintenant de _la norme du projet_, ça sera plus simple pour eux.

Je te propose d'utiliser [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) qui fera le plus gros du boulot pour le PSR-2 :

    # Téléchargement de l'utlitaire
    curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar

    # Usage
    php phpcbf.phar  --standard=PSR2 -np --tab-width=4 --encoding=utf-8 .

Pour les autres erreurs que l'outil n'aurait pas réussi à corriger, s'il y a un soucis, n'hésite pas à ouvrir une issue. Tu peux voir la méthode de validation du code dans le fichier `.travis.yml` si tu souhaites tester un patch avant envoi.

Voilà, j'espère ne pas passer pour un tyran, mais faut bien que la transition se fasse :)

**Comment by remrem** [comment]
Ok.
