### ISSUE TITLE
Installation : liens et articles par défaut

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#113]
Après installation il y a des articles et liens par défaut, serait peut-être bien de revoir un peu ça, histoire d'être raccord avec la nouvelle direction de blogotext ?

**Comment by BoboTiG** [comment]
Complètement ! On peut carrément utiliser des informations génériques, pas besoin de citer de nom ou de vraies URL.

**Comment by remrem** [comment]
Je te laisse la main dessus ?

**Comment by BoboTiG** [comment]
Je n'aurai du temps que demain, si d'ici là tu as des idées, n'hésite pas :)

**Comment by BoboTiG** [comment]
PAs très sexy, mais ça tiendra dans le temps, plus besoin de s'en préoccuper :)
