### ISSUE TITLE
addon - système de hook

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#120]
Je retente ma chance (changement de chef de projet ^^), concernant le système de hook dont j'avais lancé l'idée dans #70, j'ai toujours le code, j'ai continué de bosser tranquillement dessus, et je pense que ça pourrais lever quelques limitations du système de plugins actuel (accès aux articles, links...), meilleure intégration dans les templates...

Point de vue hook, on les place où l'on veut et on peux limiter l’accès aux données (hors GLOBAL, POST, GET... quoiqu'il y ait des solutions...) afin de limiter les abus sur les plugins. Et, soyons fou, on pourrait autoriser les plugins à avoir accès à certaines parties de l'administration (piwik, GA...) pour étoffer un peu le dashboard de l'administration.

Point de vue performance, du moment que le plugin n'utilise pas des regex à la pelle, ça tourne bien.

Pour infos, j'ai assez avancé sur un plugin autorisant l'utilisation d'image dans les chapo (blog photo/galerie), un autre plugin concernant l'URL rewriting ...

Tournée Générale de testing ? :D

**Comment by BoboTiG** [comment]
Ça m'a l'air très intéressant ! Fais péter la tournée de tests ! :)

**Comment by remrem** [comment]
J'essaie de faire un clean up des modifs + addons et de pousser ça aujourd'hui, je pousse sur la branche dev ou tu mets en place une branche testing ?

**Comment by BoboTiG** [comment]
Pousse sur la dev, on ne sortira une version stable que lorsque les aidons seront implémenter à 100%.

**Comment by remrem** [comment]
cf. #129 

Je développerai des exemples concrets d'utilisation du hook aujourd'hui (wiki de github ou ailleurs).

Petite explication rapide : 

le système de hook se compose d'une partie dédiée à la déclaration d'une action à déclencher lors de l'appel d'un hook, une autre partie dédiée à l'appel au hook et une dernière partie au contrôle (sommaire) de la sortie de l'appel du hook (optionnel).

déclaration d'une action à déclencher lors de l'appel d'un hook : 
`hook_push($hook_name, $function, $priority = 10)`

- $hook_name, string, le nom du hook
- $function, string, le nom de la function à appeler
- $priority, int, la priorité (ordre) d’exécution (il faut encore que je bosse un peu dessus pour éclaircir)

appel d'un hook : 
`hook_trigger($hook_name)`

- $hook_name, string, le nom du hook
Note : tous les paramètres additionnel seront accessible aux fonctions déclenchée par cet appel sous forme d'un tableau.

Struture de contrôle (optionel) : 
`hook_check($hook_name, $args_count, $args, $must_die = true)`

- $args_count, int, le nombre total d'arguments passé lors de l'appel ($hook_name compris)
donc `hook_trigger('nom_du_hook')` compte 1 argument, `hook_trigger('nom_du_hook', $variable )` en compte 2
- $args, array, le tableau de retour lors de l'appel du hook_trigger
- $must_die, bool, die() dans le cas où quelques choses ne va pas dans le contrôle, si $must_die = false, alors la fonction hook_check renverra false

Exemple complet

```
<?php

// on appel le système des addons, qui lui chargera tous les addons (voir plus bas)
include 'addons.php';

// l'argument que l'on veut travailler
$notre_argument = 'La vie est belle';

// on lance le hook
$retour_hook = hook_trigger('id-du-hook' , $notre_argument );

// on vérifie que rien ne cloche
if (hook_check( 'id-du-hook' , 2, $retour_hook , false) !== false ) {
    // tout va bien, on peux modifier la variable que l'on souhaitai travailler
   $notre_argument =$retour_hook['1'];
}

echo $notre_argument;
// si le hook a bien fonctionné : La vie est belle quand il ne pleut pas...
// sinon : La vie est belle

```

Dans un addon : 

```
<?php

/**
 * ... config de l'addon ...
*/

// on accroche une fonction à un hook
hook_push( 'id-du-hook' , 'la_function_de_notre_addon');

function la_function_de_notre_addon( $arguments )
{
     // $arguments['0'] contient le nom du hook
     // $arguments['1'] contient la variable '$notre_argument'
     $arguments['1'] .= ' quand il ne pleut pas...';

     // on renvois les arguments
     return $arguments;
}
```

Voilà, c'est basique comme exemple, il y a des cas qu'il faudrait expliqué pour facilité la compréhension : 
- plusieurs arguments de travail
- le respect du format (tableau) des arguments dans les fonctions appelées par un hook
- déclaration de plusieurs fonction à appeler avec/sans priorité
- les limitations (j'ai eu des questions...), par exemple qu'une "fonction à appeler" déclarée après le déclenchement du hook ne sera pas appelée ...

**Comment by remrem** [comment]
je pousse un ou deux plugins qui utilise les hooks pour plus de compréhension/exemples.

**Comment by remrem** [comment]
Sur le [wiki](https://github.com/BoboTiG/blogotext/wiki/[FR]-les-hooks,-introduction-et-informations-utiles), je ne serais pas contre une relecture ;)

**Comment by BoboTiG** [comment]
C'est parti ! Merci :)

**Comment by BoboTiG** [comment]
Je pense que dans la liste des hooks, on devrait dire où chaque hook est appelé.

**Comment by remrem** [comment]
J'y ai pensé et je me suis dis que pour l'instant ça serait une information temporaire (roadmap v4) et que ça risque de pas mal changer dans les prochains jours/semaines...

**Comment by BoboTiG** [comment]
D'accord.

**Comment by remrem** [comment]
J'ai trouvé un petit problème dans la déclaration des hooks dans les addons.

A l'heure actuel, les hook-push sont déclarés après `$GLOBALS['addons'][]`, or, si le plugin est désactivé, les hook-push sont quand même exécuté...
Je suis dessus.

**Comment by BoboTiG** [comment]
Attends 30 sec, je pousse la MàJ pour l'activation.

**Comment by BoboTiG** [comment]
C'est good !

**Comment by remrem** [comment]
Je ne vois que deux solutions possible, j'aimerai un avis :

1. j'ajoute un premier paramètre à la `function hook_push()` qui doit être le nom du module et lors du hook-push, la fonction vérifie que l'addon est bien actif avant d'enregistrer le hook-push.
L’inconvénient reste la syntaxe ```
hook_push( 'nom_du_module' , 'UID_du_hook' , 'fn_callback_name' , $priority );
```
2. au lieu de faire des hook-push directement depuis la fonction, on ajoute les hook-push dans le tableau `$GLOBALS['addons'][]` tel que : 
```
$GLOBALS['addons'][] = array(
    'tag' => 'stupid_cache',
    ...
    'hook-push' => array(
        'UID_du_hook_1' => array(
            'fn' => 'fn_callback_name',
            'priority' => 200
        ),
        'UID_du_hook_2' => array(
            'fn' => 'fn_callback_name_2',
            'priority' => 200
        ),
```

Du coup, 1 ou 2 ou autre solution ?

**Comment by BoboTiG** [comment]
La 2, et pour ne pas trop encombrer, tu peux rendre optionnel `priority` (200 par défaut apparemment). Et peut-être que `callback` serait plus approprié que `fn` ?

**Comment by remrem** [comment]
Ok
