### ISSUE TITLE
ré-organisation du core

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#121]
à force de parcourir le core de blogotext, je me dis qu'il y a des petites choses à corriger à droite et à gauche, ne voulant pas imposer ma logique, j'ai fait un exemple avec l'install : 
- déplacement de function(s) utilisée(s) uniquement pas l'installation
- renommage des functions propre à l'installation
- ajout/modification de commentaires dans le code
- ...

Rien de bien transcendant en soit, ça relève plus de la micro optimisation, mais ça ne mange pas de pain et ça peu être fait par étapes sans trop chambouler le core.
Je pousse un PR, à commenter, à valider ou à rejeter...

**Comment by BoboTiG** [comment]
Ça me convient parfaitement :)
