### ISSUE TITLE
erreur fichier lang et RSS

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#123]
sur une installation fraîche de la branche dev, la lecture du flug RSS retourne une erreur due à la contante DIR_ADDONS qui est utilisée dans les fichiers langs, mais sans être définie.

**Comment by remrem** [comment]
Potentiellement même bug pour le flux atom (non testé)
bug fixe : juste changer l'ordre des includes dans atom.php et rss.php
#124

**Comment by BoboTiG** [comment]
Nickel, merci !
