### ISSUE TITLE
Feuille de route

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#126]
Question qui me travaille depuis deux jours, serait possible d'avoir une feuille de route pour sortir une version stable ?
Histoire d'avoir un peu de visibilité ...

**Comment by BoboTiG** [comment]
Pas facile, mais en gros :
- prochaine version stable, v3.7, sortira quand les addons seront implémentés et auront été testés à fond.
- dans l'idéal, le refactoring de chaque fichier comme tu as fait pour le core, mais je pense qu'on peut déléguer pour les versions suivantes 3.7.x. S'il n'y a pas de gros changements qui casse la rétro-compatibilité,  sinon ça sera pour une 4.0.
- Pour la prochaine prochaine version majeure a venir, tout traduire en anglais (commentaires, fonctions et noms de fichier). Ça va faire un sacré boulot.
- Enfin, pour encore plus tard, ajouter le multilingue. Bien plus tard, ça n'est pas du tout une priorité.

Mais rien n'est définitif. Qu'en penses-tu ? Tu vois d'autres chosds

**Comment by remrem** [comment]
Ok, ça me semble déjà pas mal. En gros, on part pour étendre blogotext à l'international (core + public) ;)

Juste quelques question/suggestions :

- Pour le refactoring, je pense qu'il faudrait séparer au maximum le core en deux/trois parties (public/admin/commun), là c'est un peu le bordel (à mon goût) dans /inc/...
Pour illustrer mon propos, rien que dans /inc/form.php on a du public et de l'admin, il serait peut-être mieux de séparer tout ça. En là jouant bien, ce que l'on perd en include/require (deux includes au lieu d'un seul) sera gagné sur le code à charger/interpréter... Je pense qu'on peux travailler ça assez rapidement.

- le système de template aurait aussi besoin d'être un peu retravaillé, dans la version actuelle, je me sens un peu limité sur certaines choses juste en ajoutant/modifiant 2 ou 3 choses, ça pourrait ouvrir certaines perspectives...

- Pour le multilingue, côté client/public, genre http://example.tld/fr/ http://example.tld/en/ ?
Parce que ça, je pense que c'est faisable via un addon + hook, tout dépend des emplacements et de la portée des hooks dans le core. Ça permettrait de garder un core léger et d'avoir des plugins pour étendre le core au besoin ou on essaie d'intégrer le maximum de chose directement dans le core ?

- Point de vue config / cache / database / files. J'aimerais bien réorganisé un peu tout ça, histoire de pouvoir faciliter les sauvegardes/migrations/updates et pouvoir avoir plusieurs vhost apache qui tape sur la même installation de blogotext. Par exemple, déplacer /cache/, /config/, /databases/, /files/ ... dans /vars/example.com/

- Il faudrait aussi mettre en place quelque chose (documentation/wiki/FAQ/INSTALL.txt ?), même en partant sur du léger, mais avoir un espace où expliquer certains rouages...

**Comment by B4rb3rouss** [comment]
Si je puis me permettre une petite idée au sujet des templates. Il serait intéressant de disposer d'une interface pour modifier l'apparence du blog par glisser/déposer des divers éléments (articles, sidebar, addons...). Rien de bien compliqué, mais qui serait plus simple que l'édition à la main du fichier list.html.

Le code CSS est aussi relativement compliqué, mais j'ignore si on peut le simplifier tout en gardant un thème par défaut aussi classe. Au pire, une modification simplifiée des couleurs pourrait passer par un addon, ça devrait pouvoir se faire si je ne me trompe pas.

Très encourageant en tout cas ces idées !

**Comment by BoboTiG** [comment]
Vous avez plein de bonnes idées. Je répondrai demain correctement, je n'ai pas le temps aujourd'hui. Mais tout ça augure de bonnes choses :)

**Comment by BoboTiG** [comment]
Alors, @remrem :
* __refactoring__ : à 100% d'accord. Il faudrait un dossier `inc` pour l'admin, et le `inc` actuel pour le public.
* __template__ : on pourrait partir sur Smarty, on ne va pas tout réinventer. Avez-vous d'autres suggestions ?
* __multilingue__ : ça me convient très bien, moins le core est chargé, mieux ça sera pour tout le monde.
* __config__ : on pourrait créer le dossier `data` qui contiendrait tout ce qui est relatif à l'installation actuelle. Ensuite, ajouter une constante `DATA_FOLDER` et adapter les autres en fonction. Ça irait ?
* __wikis__ : je viens d'activer le Wiki.

@B4rb3rouss, c'est pratique mais ça serait tout un chantier à créer. Peut-être que ça pourrait être une application tierce qui générerait les fichiers JS/CSS/HTML mais ça ne serait pas intégré à BlogoText. Ou du moins, pas dans les prochaines versions, il y a beaucoup de travail à terminer avant de pouvoir l'envisager.

**Comment by remrem** [comment]
pour le **template**, méh ... idéalement il faudrait que plus de monde donne son avis, c'est un peu subjectif comme sujet.
Personnellement, je dois avouer que le côté kiss de blogotext me plait bien ... c'est rapide, ça fait le boulot et il ne manque pas grand chose pour l'étendre, donc je ne suis pas trop chaud pour du smarty, dwoo, twig ...
Une idée, sans doute à la c*n, le core sort les données d'un article (tableau ou object...) et les balances directement au template via une fonction ou une classe, et, à charge du template, de charger son moteur et de formater les données pour les faire correspondre à son moteur. Point de vue core, ça allège (si on laisse tomber le système de template actuel), plus facile (théoriquement) à maintenir et chaque développeur de template fait en fonction de ses goûts/envie/besoins. A creuser ?

pour la **config / temp / cache**, peux importe le /[data|datas|vars]/, moi ce qui m'intéresse aussi c'est le sous répertoire par blogotext (nom de domaine ou id), c'est juste jouer sur une variable, ça n'as pas de grandes conséquences sur la complexité/poids du core. Pour reprendre ton exemple : 
`define( 'DATA_FOLDER' , BT_ROOT.'var/' );`
deviens (en gros) : 
`define( 'DATA_FOLDER' , BT_ROOT.'var/'. strtolower(htmlspecialchar( $_SERVER['HTTP_HOST'] )) );`
( je risque d'être insistant là dessus :D d'autant plus qu'il m'a semblé voir un ticket à ce propos #24  )

**Wiki**, cool :D

**Comment by BoboTiG** [comment]
Si chaque développeur doit maintenair son système de **template**, c'est pas gagné. Que proposes-tu pour étendre le système actuel ?

Si je comprends bien, pour les **fichiers de config**, il y aurait :
- `BT_ROOT/var/www.example.org`
- `BT_ROOT/var/blog.ceci.cela`

Et tu as des `vhosts` qui pointent vers la même installation de BT ?

**Comment by remrem** [comment]
pour le template, dans l'immédiat, il n'y a juste que quelques tags à ajouter (pour les besoins que j'ai identifié, à voir avec la communauté).

Pour les fichiers de config, oui, c'est bien ça, pour étayer :
```
BT_ROOT/var/www.example.org/config/
BT_ROOT/var/www.example.org/cache/
BT_ROOT/var/www.example.org/databases/
BT_ROOT/var/blog.ceci.cela/config/
BT_ROOT/var/blog.ceci.cela/cache/
BT_ROOT/var/blog.ceci.cela/databases/

```
et idéalement
```
BT_ROOT/var/www.example.org/files/
BT_ROOT/var/www.example.org/img/
BT_ROOT/var/www.example.org/addons/
```

> Et tu as des vhosts qui pointent vers la même installation de BT ?

Actuellement non, mais j'ai plusieurs blogotext en prod ou en préprod, et rien qu'à l'idée de devoir faire le tour pour les maj, sauvegarde, réplications (sur 4 serveurs) et la maintenance, ça me gonfle déjà...

**Comment by BoboTiG** [comment]
Tout semble faisable, ça me plait bien. Seul bémol : les addons.
Étant donné qu'on ne peut pas les installer comme on le souhaite, c'est un dossier synchronisé avec le dépôt des addons. Ce qui est envisageable, c'est de stocker les paramètres (`params.ini`) et l'état (`.enabled`) dans `BT_ROOT/var/www.example.org/addons/`seulement.

**Comment by remrem** [comment]
Pas faux ;) et plus léger pour les sauvegardes/réplications ;)
