### ISSUE TITLE
http header

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#128]
Manque le header HTTP 404 qui va bien...

**Comment by BoboTiG** [comment]
C'est un mémo pour toi ?

**Comment by remrem** [comment]
plus global, si quelqu'un veut s'en charger ...

**Comment by remrem** [comment]
J'ai fait une première passe sur la partie publique en déclarant des 404, ils faudra vérifier...

**Comment by BoboTiG** [comment]
Ça marche !

**Comment by BoboTiG** [comment]
Peux-tu détailler un chouilla sur celle-ci ?

**Comment by remrem** [comment]
J'ai modifié `/index.php` pour : 
- ajouter des tests conditionnels (item found) (à vérifier)
- ajouter des http_response_code(404); là où il me semble que rien n'a été trouvé...

**Comment by remrem** [comment]
Je me demande si on ne devrait pas laisser dans l'état pour la 3.7, point de vue index, c'est un peu trop compliqué à gérer sans avoir fait un refactoring... par exemple un `?mode=pioupiou` retourne l'index du blog sans 404... là si je creuse plus loin, ça va me soûler et je vais finir par tout réécrire ^^

**Comment by BoboTiG** [comment]
Je ne pense pas que l'on soit obligé d'ajouter toutes ces vérifications. Si l'URL ne correspond en rien à ce que l'on propose, on retombe sur l'index.
Au mieux, on peut définir une page d'erreur 404 dans le `.htaccess` qui redirigerait vers `index.php?error=404` où on affiche le blog et un message d'erreur. Non ?

**Comment by remrem** [comment]
Ok. du coup je laisse dans l'état.
