### ISSUE TITLE
[addon] bouton d'action

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#130]
Proposition d'ajout de bouton d'action concernant le plugin depuis l'interface d'administration.

Si un plugin utilise une BDD ou un cache propre (...) il serait bien de pouvoir depuis l'administration de blogotext > module pouvoir appeler des fonctions interne d'un addon
par exemple, dans le tableau de déclaration :

```
$GLOBALS['addons'][] = array(
    'tag' => 'stupid_cache',
    'action' => array(
         'title' => array(
                  'fr' => 'vider le cache',
                  'en' => 'empty the cache'
         ),
         'fn' => 'addon_stupid_cache_clean_cache',
         'level' => 'warning', // info = bouton normal, warning = bouton orange, danger = bouton rouge
    )
   ...
```

**Comment by BoboTiG** [comment]
Ça serait dans les paramètres de l'addon ?
Je pense qu'il faudrait aussi la possibilité soit de réinitialiser les paramètres (suppression du fichier `params.ini`), soit d'afficher la valeur par défaut de chaque option.

**Comment by remrem** [comment]
un bouton "reset" à côté des boutons annuler et enregistrer pourrait être pas mal ...

> Ça serait dans les paramètres de l'addon ?

Dans le tableau $GLOBALS['addons'][], plus précisément : 
$GLOBALS['addons'][]['action']
en plus de 
$GLOBALS['addons'][]['config']

Histoire d'avoir le tableau $GLOBALS['addons'][] qui contient tout ce qui peux/doit être "connecté/interféré" directement a l'administration depuis l'interface et le core de blogotext

**Comment by BoboTiG** [comment]
Les différents boutons seront affichés dans la page des paramètres de l'addon eux aussi ? Dans un second cadre pour ne pas tout mélanger ?

**Comment by remrem** [comment]
pour les boutons du $GLOBALS['addons'][]['action'], oui, dans la page des paramètres, histoire de garder la liste des plugins "propre", surtout si des plugins utilisent 3-4-5(...) boutons ...

**Comment by BoboTiG** [comment]
Ça me va. Est-ce que le nom des fonctions peut être `cache_clean_cache` seulement ? Ça sera du côté de BT à concaténer le nom de l'addon avec le nom de la fonction pour avoir le réel non de  la fonction à appeler. Ça éviterait d'avoir à tout renommer en cas de changement de nom de l'addon et d'avoir des noms à rallonge. Ça te convient aussi comme approche ?

**Comment by remrem** [comment]
Oui, pas mal, mais en allant un peu plus loin, c'est le core qui fournir le path du cache à l'addon ex: '/datas/toto.tld/cache/addon_name/'.
Ainsi, on peux proposer un fonctione pour nettoyer tout le cache d'un coup (ou par addon), autant pour le cache du core que pour le cache des addons. Le dev d'un addon n'as pas à s’embêter à créer/maintenir sa fonction de cache, juste à faire un `cache_clean_cache('nom_de_son_addon');`

Tu en penses quoi ?

**Comment by BoboTiG** [comment]
Il y a de l'idée :)
Mais tous les addons n'utiliseront pas de cache, il faudra adapter la visibilité du bouton. Et dans l'addon en lui-même, comme le dev saura où stocker les fichiers en cache ?

**Comment by remrem** [comment]
une fonction à appeler pour avoir son path de cache, par exemple : 
`$cache_path = cache_get_path('nom_de_son_addon');`
Après, il organise son cache comme il veux :
```
$cache_path .'/toto/';
$cache_path .'/tata/';
```

pour vérifier si un addon utilise un cache, un simple :
`is_dir(cache_get_path('nom_de_son_addon'));`

**Comment by remrem** [comment]
Pour faire le point sur les boutons : 
- la solution que j'ai proposé (form + actions à la chaine), on garde ou on mets de "vrais boutons" ?
- mettre en place un système via ajax ou autres afin que les actions ne soient pas exécutée sous le compte utilisateur admin (sécurité et empêche de défacer la page admin avec les résultats des actions)

**Comment by BoboTiG** [comment]
Ta première solution semble correcte. PAs besoin de surcharger le bouzin.

**Comment by remrem** [comment]
Dans les 2 cas (form ou boutons), il faudra passer par une méthode pour dissocier du rechargement de la page, risque de défaçage de la page admin. point de vue performance, ça reste de la "maintenance", donc que l'utilisateur clique sur 3 boutons ou qu'un script enchaîne 3 fonctions, je ne vois pas trop la différence. A mon sens, faut plus faire de l'éducation/conseille : "En effaçant intégralement le cache, votre blogotext peux souffrir de ralentissements le temps de régénérer votre cache, nous vous conseillons de faire cette opération hors de période de pointe"...

**Comment by BoboTiG** [comment]
Donc on garde comme c'est là, c'est bien.

**Comment by remrem** [comment]
@BoboTiG , tu peux ré-ouvrir cette issue, le temps de vérifier la mise en place de la délégation ajax/PHP, la sécurité...

**Comment by remrem** [comment]
@BoboTiG 


1. je peux avoir ton avis sur le process ajax/json et le choix esthétique (loading, affichage des retour des boutons), histoire de savoir si je finalise ou si je reprends ?

2. Et question, pour l'instant, je pars du principe que la fonction de callback renvoie true ou false. Et je me dis que ça pourrais être pas mal d'autoriser le module à ajouter un commentaire. Tu en penses quoi ?

Par exemple, sur un addon d'URL rewriting, je mets en place un bouton pour créer l'index des urls, si je peux renvoyer depuis la fonction de callback pour informer par exemple que "X url était déjà dans l'index et que leurs URL n'ont pas été modifiée", ça pourrais être pas mal.

Du coup, on demande au dev que leur fonction de callback retourne au choix :       
`true` ou  `false` ou             
 ```
array(
       success => bool
       message => string
    )
```

**Comment by BoboTiG** [comment]
Esthétiquement parlant, ça claque, j'aime bien.
Pour les données renvoyées, peut-on envisager un retour `mixed` ? Genre `true`, `false` ou `string` contenant le message échappé.

**Comment by remrem** [comment]
string, n'indique pas si succès ou non :/

**Comment by BoboTiG** [comment]
Si pas succès, alors `false`. Sinon, partons sur ton idée :

    array (
        succes => bool,
        message => string
     )

Si `message` est non vide, on l'affiche. C'est ça ou tu souhaites pouvoir renvoyer un bolléen en plus de ça ?

**Comment by remrem** [comment]
je pense implémenter le bool et l'array, histoire de ne pas forcer les dev à déclarer des array alors qu'un bool leur suffit. L'array, c'est plus pour donner une info ou développer un message d\'erreur.
Je devrais pouvoir pousser ça d'ici demain.

**Comment by BoboTiG** [comment]
OK !

**Comment by remrem** [comment]
SI c'est bon pour toi, tu peux clôturer.
