### ISSUE TITLE
Addons : fichier d'activation

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/blogotext#131]
Actuellement,  tous les addons sont activés par défaut et on désactive ceux qu'on ne veut pas. C'est bancal, surtout si on se retrouve avec une tripotée d'addons.
Pour corriger le tir, on devrait partir sur : tous les addons sont désactivés par défaut, et on active ceux qu'on souhaite.
Est-ce que ça te convient @remrem ?

**Comment by remrem** [comment]
Ok, de même, par défaut, pas de fichiers "params.ini" serait pas mal

**Comment by remrem** [comment]
J'ai jeté un coup d'oeil et je propose la solution suivante : 
Actuellement les addons sont désactivés par un fichier ".disabled", pourquoi ne pas faire le contraire, avoir un fichier ".enabled" ? Ainsi par défaut, pas de fichier, pas d'activation et je pense que l'on peux ajouter une 
règle sous github via un fichier ".ignore" pour empêcher le téléchargement ?

**Comment by BoboTiG** [comment]
C'est exactement ce que j'avais en tête.
Pas besoin de la règle pour `.gitignore`, on activera 1 ou 2 addons "officiellement" comme le calendrier.

**Comment by BoboTiG** [comment]
Je m'en occupe si tu n'es pas déjà sur le coup.

**Comment by remrem** [comment]
Tu peux y aller
