### ISSUE TITLE
[WIP] Addons

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/blogotext#134]
Pour rester à jour, voici ce qu'il reste à faire, das le désordre :
- [x] Revoir la façon dont ils sont activés (#131)
- [x] Système de hooks (#120)
- [x] Boutons d'action (#130)
- [x] Versioning (#127)

**Comment by remrem** [comment]
> Boutons d'action
je peux m'en occuper cet après-midi

**Comment by BoboTiG** [comment]
Je viens d epousser 2 MàJ sur les paramètres, je te laisse le champ libre.

**Comment by BoboTiG** [comment]
Tant que tu es dedans, et vu que chaque nom des addons est unique (et doit l'être), peut-être que faire 

    $GLOBALS['addons']['calendar'] = array(...);

serait plus accessible (et performant en théorie car moins de _lookup_) que 

    $GLOBALS['addons'][] = array(
        'tag' => 'calendar',
        ...
    );

Non ?

**Comment by remrem** [comment]
J'avais même pensé à 
```
$addon_declaration = array(
    'tag' => 'calendar',
    ...
);
```
la fonction de load que je développe traite les addons les uns après les autres et mets en place proprement `$GLOBALS['addons']['calendar']`,


J'ai même pensé à mettre ça dans un fichier à part, histoire de ne pas charger toutes les fonctions d'un addon juste pour avoir sa config, faut que j'y réfléchisse...
`/addons/calendar/addon_declaration.php`
```
$addon_declaration = array(
    'tag' => 'calendar',
    ...
);
```

**Comment by BoboTiG** [comment]
J'y avais pensé aussi, mais le nom du fichier est trop long, `(config|addon).php` ? Et le nom de la variable, idem.

**Comment by remrem** [comment]
```
$declaration = array(
    'tag' => 'calendar',
    ...
);
```
Le coup de la séparation dans un autre fichier n'est pas terrible.
Là tout en 1 fichier, permet de vérifier la version avec celle qui est en cache (en cas d'update via ftp)...

**Comment by BoboTiG** [comment]
`$declaration` :/
En anglais ça passe ou c'est le genre difficilement traduisible ? C'est pas sexy :)

**Comment by remrem** [comment]
(en anglais, declaration)[https://translate.google.fr/#fr/en/d%C3%A9claration] :) si tu as mieux...
`$settings` est redondant vu qu'on se retrouverai avec `$settings['settings']` non ?
ou tout simplement `$addon` ou `$this_addon` ...

**Comment by BoboTiG** [comment]
C'est good pour déclaration.

**Comment by BoboTiG** [comment]
Je ferme car c'est implémenté. On ouvrira de nouvelles issues en cas de soucis.
