### ISSUE TITLE
RemRem le contributeur

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/blogotext#137]
Petit mémo pour que tu penses à t'ajouter au fichier CONTRIBUTORS :)

**Comment by remrem** [comment]
vui.. je fais ça avec le prochain PR qui ne serait tarder (je boucle mes tests/debug)

**Comment by remrem** [comment]
PR #144 , comme ça tu peux fermer cette issue ;)

**Comment by BoboTiG** [comment]
:)
