### ISSUE TITLE
CSS top menu

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#138]
Je ne sais pas si c'est voulu, mais le menu déroulant en haut à droite (celui avec les modules...) reste au dessus de l'icone d'avatar, il n'y a pas mort d'homme, mais je tique à chaque fois ... Comportement normal ou bug ?
Je n'ai pas trop regardé/testé, mais apparemment `#top > #nav-acc > ul{margin-top:119px;}` règle le problème.

Je ne préfère pas trop mettre les mains dans le css de l'administration pour l'instant, si quelqu'un s'en veux s'en occuper...

**Comment by BoboTiG** [comment]
C'est voulu, comme pour le menu sur chaque commentaires.

**Comment by remrem** [comment]
Ok.
