### ISSUE TITLE
Du PR et du gros

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#140]
Concernant le PR #139 

En vrac : 
1. #130 à revoir, pas réellement mis en place des **boutons pour les addons**, mais là ça permet d'enchainer plusieurs actions. J'ai remarqué aussi un comportement qui n'est pas terrible, le bouton lance une fonction en callback, mais si la fonction affiche du texte ou pire, ça se répercute sur la partie admin et du coup avec les droits admin. Peux-être une exécution via ajax, sans ouvrir la session administrateur...
Sois on change pour des "vrais boutons" soit on garde comme ça, quitte à changer `$GLOBALS['addons'][]['button']` en `$GLOBALS['addons'][]['admin_action']` (ou autres).

2. #120 - modification des **hook des addons** pour les passer dans `$GLOBALS['addons'][]`

3. un peu de **refactoring**, j'ai rapproché la plupart des functions le plus prés possible de leur cible (admin) et lorsque seul un fichier .php appelle une fonction, je les déplacé dans le fichier php, l'objectif étant d'éclater les fonctions pour définir au maximum les dépendances. Par la suite, on aura plus de visibilité pour ré-organiser tout ça ;)

4. Préparation de la **v4** + mise en place partiel du **/var/domain.tld**, j'ai essayé de faire ça bien, avec le support de plusieurs cas de figure : 
```
http://toto.com => /var/toto-com/
http://t.oto.com => /var/t-oto-com/
http://toto.com/blog1/ => /var/toto-com-blog1/
http://toto.com/blog2/ => /var/toto-com-blog2/
例如.中国 => IDN => xc---dfsf--sdqfsd-- (ou un truc dans ce genre)
سجل.السعودية/admin/ => IDN => xc--sfsdf--sdvcnyd--admin (ou un truc dans ce genre)
```
Plus le support des domaines et path avec des accents + international (chinois, arabe...) ... en principe, ça devrait le faire sans risque de colision (ou alors vraiment pas de bol ...)
J'ai essayé de sécuriser ça au maximum en travaillant avec `_REQUEST['HTTP_HOST']` (qui peux être "hacké"), les dossiers /var/ déjà existant et `$GLOBALS['racine']`, si ce n'est pas suffisant, j'ai d'autres pistes, mais il me semble que ça serait sortir l'artillerie lourde pour un mouche ... Pour l'instant, cette partie se découpe en "global" + ( "<4.0" ou ">= 4.0" ), le ">= 4.0" nécessitera un coup de polish...

5. rapport au 4. concernant les **addons**, le fichier de config, cache (en récupérant le path via `addon_get_cache_path()`, le vidage du cache via l'administration et le .enable utilisent le **/var/domain.tld**

6. J'ai ajouté une fonction `get_path()` dans `inc/file-system.php` qui retourne le **path absolu** point de vue serveur (par exemple : `/inc/auth.php` => `/var/www/blogotest-dev/web/inc/auth`, si vous utilisez cette fonction regardez le commentaire, il y a des paramètres de vérification et de debug, c'est basique, pas très propre, mais ça évite de se tirer les cheveux. Point important, le path que vous soumettez doit être absolute depuis le répertoire d'installation de BT, par exemple :
```
/inc/auth.php => /var/www/blogotest-dev/web/inc/auth.php
/admin/inc/tpl.php => /var/www/blogotest-dev/web/inc/auth.php
./inc/auth.php => ne sera pas valide, pour du debug, voyez les paramètres de la fonction
```

7. Le **path absolut** est défini tel que : 
`DEFINE( 'BT_DIR' , dirname( __file__ , 2 ) . '/' );`
Si vous avez mieux / plus fiable, n'hésitez  ;)
**upd** depuis `/inc/conf.php`, d'où le `dirname( __file__ , 2 )`

8. les **nouvelles constantes** : 
`BT_DIR` => chemin absolu `/var/www/blogotest-dev/web/`
`DIR_VAR` => chemin relatif `BT_ROOT.'var/domain-tld/`
`DIR_VAR_ADDONS` => chemin relatif `DIR_VAR.'addons/`
**upd** `BT_DIR` peux être renomé, j'ai mis ça pour rester cohérent avec `BT_ROOT`

9. fichiers et dossiers, quelques création, suppression et renommage, je pense que c'est assez lisible sans devoir détaillé, me signaler ou modifier si ça ne conviens pas
**upd** C'est juste du renommage, déplacement de fonctions et fichiers, je n'ai pas touché au comportement des fonctions

10. Fix à l'arrache concernant les includes depuis /admin/ : 
`/admin/` va include `/admin/inc/inc.php` qui va `include /inc/inc.php`, c'est très propre, mais en attendant ça fait le job.

11. Si vous pouviez faire 1 ou 2 bench sur l'index + article sur la partie public (chrono dans le code source HTML en bas de page est suffisant), histoire de confirmer mon impression que c'est un poil plus rapide, léger...
**upd** ou à défaut confirmer que les performances ne sont dégradée...

12. J'oublie des choses ... 

13. Il faut mettre à jour le test dans la liste des addons dans l'administration pour afficher ou non le lien vers les "paramètres" d'un addon

**upd**

14. J'ai refais `rss.php` et `atom.php` > `flux.php`, quelques problèmes à régler et je commit
**upd** ça devrait être bon

15. hum, j'ai merd*uillé, je n'ai pas poussé dans le commit la suppression des fichiers...
**upd** ça devrait être bon

**Comment by remrem** [comment]
Pour info, j'ai mis à jour le plugin stupid_cache , cf PR#11 sur blogotext-addon.
J'ai mis en place le bug pour l'espace admin > boutons ;)

**Comment by BoboTiG** [comment]
Avant tout, merci pour cette PR, elle pèse !

1. À surveiller oui.
2. OK.
3. Nice.
4. Juste nickel. Est-ce, pour faire plus simple, il aurait été préférable d'encoder/hasher le TLD tout simplement ? Un genre de base64 ou sha1.
5. OK.
6. Dans les includes de la partie admin, `/inc/auth.php` retourne `/inc/auth.php`. J'investiguerai ça juste après.
7. Très bien. Cette constante sera utilisée à foison : gain en performances pour toutes les inclusions / vérifications sur les fichier et dossiers.
8. Du coup, est-ce que `BT_ROOT` ne devrait par être `BT_DIR` ?
9. OK.
10. OK temporairement.
11. Je m'y colle.
12. Pas de soucis, c'est normal !
13. OK, TODO.
14. OK.
15. OK.

**Comment by BoboTiG** [comment]
J'ajoute que la partie `var/tld/addons` fait trop de boulot, voici ce que ça génère :

    - var/192-168-0-10
       - addons/
          - calendar/
              - index.html
       - CONTRIBUTING.md/
              - index.html
       - index.html
       - LICENSE.txt/
              - index.html
       - light_seo/
              - index.html
       - plugin_example/
              - index.html
       - README.md/
              - index.html
       - readmore/
              - index.html
       - relatedposts/
              - index.html
       - smileys/
              - index.html
       - stupid_cache/
              - index.html

1. Par défaut, aucun dossier ne doit être crée.
2. Je pense que, tant qu'un addon n'est pas activé ni n'a de paramètres personnalisés, son dossier ne doit pas non plus être crée. Quand on l'active, on crée, si besoin, son dossier et ajoute le fichier `.enabled`. Idem lorsqu'on met des paramètres non ceux par défaut.

**Comment by remrem** [comment]
4. l'objectif est de faciliter `l’accès humain` en cas de multiple vhost
6. j'ai fait le code review et debug un peu à l'arrache ... :/
7. à vérifier qu'elle retourne la bonne valeur dans les différents environnements de dev/prod...
8. à terme, pourquoi pas, mais 2 constantes permette de faire la bascule/test en douceur (du moins pour moi) 
10. temporairement, on est bien d'accord

**Comment by remrem** [comment]
> J'ajoute que la partie var/tld/addons fait trop de boulot, voici ce que ça génère

oO, je jette un coup d'oeil ...

**Comment by remrem** [comment]
Trouvé !
c'est `addon_get_var_path()` qui par défaut check et crée le dossier de l'addon, je mets à jour (ajout d'un paramètre `$check_create = false`

**Comment by BoboTiG** [comment]
Étant donné que personne d'autre que ceux du core n'utilise les constantes (pour le moment), on peut doucement migrer la constante pour qu'il ne reste que `BT_ROOT` (son nom est clair).

**Comment by remrem** [comment]
Ok pour `BT_ROOT`

**Comment by remrem** [comment]
Pas dreamatique en soit, mais j'y pense depuis ce matin 'flux.php' ou 'feed.php' ?

**Comment by BoboTiG** [comment]
`feed.php` :)
J'ai bientôt terminé mon patch.

**Comment by remrem** [comment]
> J'ai bientôt terminé mon patch.

J’espère que je ne t'ai pas causer trop d'arrache de cheveux :D

va pour `feed.php`, je le fais après ton patch si nécessaire,

**Comment by BoboTiG** [comment]
Bon, je pousse la PR mais il y a 2-3 coquilles. Notamment pour les URL du site ('/theme/default' ou pour les ficiers et images utilisés par les thèmes et dans la partie admin). J'ai bidouillé un truc dans `inc/config.php` L215, qu'il faudra revoir.

**Comment by BoboTiG** [comment]
Je mange et pourrai reprendre d'ici 1h - 1h30, fais toi plaisir en attenant :)

**Comment by remrem** [comment]
Ok, je vois ce que je peux faire

**Comment by remrem** [comment]
(je vais update ce commentaire au fur et à mesure)
- pour DONT_USE_HOOK, le explode entre () règle le problème.

**Comment by BoboTiG** [comment]
Tu as fait des mofis ou je peux m'y mettre ?

**Comment by remrem** [comment]
Je suis dessus, je reprends depuis l'installation ...
Tu veux que je te laisse la main ?

**Comment by BoboTiG** [comment]
Non, si tu es lancé continue.

**Comment by remrem** [comment]
ok.
Par contre, il faut vraiment utiliser un `boot.php` en mettant dedans `inc.php` et `conf.php`, là c'est propre, mais c'est éclaté inutilement (à mon sens)

**Comment by BoboTiG** [comment]
OK. Les deux fichiers seront fusionnés ?

**Comment by remrem** [comment]
oui

**Comment by remrem** [comment]
ça sera mieux pour la v4
J'ai réuni : 
```
// require_once 'inc/defines.php';
// require_once BT_ROOT.'inc/conf.php';
// require_once BT_ROOT.'inc/inc.php';
```
dans `/inc/boot.php`

Je mets en place un `/admin/inc/boot.php`

Du coup, pour chaque fichier qui reçoit une requête http (admin ou public), la première chose à faire c'est un `require_once 'inc/boot.php';`. et le `/inc/boot.php` se charge de tout (check config, sécurité de base, auth si admin, `/var/domain.tld/` ...). 
Pour peaufiner, par la suite, tranquillement, il faudra déplacer les include qui ne sont pas common/utils définit dans le boot vers les process qui en ont réellement besoin, à première vue, ça devrait bien se passer ;)

Je mets en place aussi des contantes URL_*, ce qui permettra de ne plus se mélanger les pinceaux avec les DIR_*.

J'avance, tranquillement, j'ai fini le debug de l'install, là je suis les fichiers et images ...

**Comment by BoboTiG** [comment]
+1 pour les inclusions suivant le besoin.

**Comment by remrem** [comment]
Je crois que j'ai fait le tour, je ne trouve plus d'erreurs, je te laisserai corrigé, je laisse les URL_* dans l'état, mais je pense qu'il faudrait revoir un peu ça ...
je passe un coup de clean up et je PR

**Comment by remrem** [comment]
- Bug de dernière minute sur la mutualisation de `auth_ttl()`, un peu trop efficace ;)
- J'ai changé quelques trucs lié à la sécurité, temporairement, ça reste sécurisé quand même ;)
- Je me suis planté dans `inc/hook.php`
- j'ai virer le test pour la détection de la partie admin
> never trust _SERVER
- point de vue image, je pense que c'est ok, à voir à l'usage.
- install.php, me casse les co*****, faut le virer d'admin, je créée une issue avec 2 ou 3 pistes à creuser

**Comment by remrem** [comment]
J'ai poussé plus loin le refactoring
1- j'ai réduis le nombre d'include
2- il y a beaucoup de fonctions de déplacées (tests rapide : pas l'air d'y avoir de casse)
3- j'en ai profité pour ajouter une fonction à /admin/feed.php (cf. #145 )
4- j'ai éclaté quelques fonctions (j'aime pas les fonctions qui font du push/upd/del juste en changeant 1 paramètres)
5- le public a été bien délesté côté code, du coup, il y a moyen de faire encore quelques petites choses pour réduire les include globaux
6- j'ai commencé à pouvoir placer des includes spécifique côté admin
7- j'ai préparé et commencé la séparation des langues admin/public (sert à rien de charger un array de 30ko lorsque la moitié ne sert pas)
8- renomage (dans la continuité) des functions, à a la longue, on les aura toutes ;)
9- j'en oublie

**Comment by BoboTiG** [comment]
Tu ne verrais pas un fichier "simple" ne contenant que les constantes, comme le feu `defines.php` ? Pour les avatars/favicons, par exemple, j'ai juste besoin de 2 constantes, si j'impore `boot.php` ça va surcharger le tout pour rien.
Pour ne pas avoir à modifier trop de lignes de code, on l'incluerai en début du fichier de boot. qu'est-ce que tu en penses ?

**Comment by remrem** [comment]
@BoboTiG pourquoi pas, mais pour l'instant je suis d'avis à tout regrouper point de vue config/boot. Pour l'instant entre la v3.7 et la v4, la logique du boot est un poil différent.
Pour la V4, certaines constantes ne pourront/devront être définies qu’après le chargement des la config de BT (user et pref) alors que pour la v3.7, on peux les définir au plus tôt.
Et je ne pense pas que la dizaine/vingtaines de constantes pèse très lourd point de vue ressource/lisibilité (avis perso).

**Comment by remrem** [comment]
@BoboTiG , je peux te contacter en PV (via ton contact dans contributor ?)

**Comment by BoboTiG** [comment]
Bien entendu :)

**Comment by BoboTiG** [comment]
Je ferme, elle commence à être bien longue cette conversation. Suffira de créer une autre issue, au besoin.
