### ISSUE TITLE
Stockage des fichiers de préférence

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/blogotext#143]
Je viens de me rendre compte d'un sale soucis de sécurité. Les fichiers où sont stockés les config/user/etc. sont des fichier INI qui devraient avoir l'extension PHP pour bloquer le téléchargement et le visionnage des infos.

Je m'en charge dans la foulée.

**Comment by remrem** [comment]
pas faux ... :/

**Comment by remrem** [comment]
on peux sans doute attendre la v4 pour le reste des `.ini`, comme ça on fait la bascule `.ini` > `.php` et `/config/` vers `/var/domain`, qu'en penses-tu ?

**Comment by BoboTiG** [comment]
Pour la 3.7 va falloir y toucher quand même. Les préférences de MySQL sont en clair... C'est trop dangeureux. Je passe au moins du `ini` au `php` pour la 3.7, ça roule ?

**Comment by remrem** [comment]
Ok pour moi.

**Comment by BoboTiG** [comment]
Voilà, c'est plus propre comme ça. Et dans la foulée, tout déplacer dans `var` peut se faire en 2-3 lignes de code modifées.
