### ISSUE TITLE
Lecteur de flux très lent

### ISSUE THREAD

**Issue by B4rb3rouss** [BoboTiG/blogotext#145]
Je me demande si ça ne le fait que pour moi, mais la partie "lecteur de flux" est très lente à s'afficher. Une fois que l'ensemble des articles est chargé c'est bon, la page n'est pas particulièrement lente, mais c'est l'affichage initial qui est très lent.
Pas moyen de trouver où est-ce qu'il y a un noeud. Mais la différence avec kriss feed est trop importante :/

Sinon, beaucoup de boulot récemment, c'est super !

**Comment by BoboTiG** [comment]
Bonne question, on s'en occupera une fois que le boulot de relecture pour les addons sera terminé. Merci pour le retour :)

**Comment by B4rb3rouss** [comment]
Je me demande si ce n'est pas la partie JS qui coince. Enfin pour l'instant c'est moi qui coince pour trouver le souci. Ça donne presque envie de piquer le code de KRISS qui est finalement plus efficace.
J'ai 73 flux différents. je joins le fichier opml.

**Comment by B4rb3rouss** [comment]
Quelques suppositions : 
- Le souci ne vient pas du fait qu'il télécharge *toutes* les articles à lire, qui ne sont pas mises en cache?
- Ajouter un système de "pages", avec par exemple "10" articles par page pourrait éventuellement réduire le temps de chargement.

**Comment by remrem** [comment]
> Le souci ne vient pas du fait qu'il télécharge toutes les articles à lire, qui ne sont pas mises en cache?
Je pense que ça viens de la, avec ta liste de flux + la mienne, j'arrive à un page d'un peu moins de 8mo et 83 requêtes, le temps pour généré la page me semble correcte, je pense que c'est plus la partie requête http + téléchargement qui est trop lourde :/

> Ajouter un système de "pages", avec par exemple "10" articles par page
Je pense que c'est la meilleure solution, vu qu'il s'agit d'un flux qui peux aller très vite, je le sens pas trop de jouer avec le cache/db du navigateur....

**Comment by remrem** [comment]
Dans le PR #147 , j'ai ajouté l'affichage des flux par tranche de 24h via 2 liens dans la colonne de gauche, c'est fait à l'arrache, mais ça permettra au moins de valider le principe. Si tu peux tester la branche dev après le que le PR soit mergé (ne teste pas en prod, il y a bcp de changement et pas mal de risque que ça merdouille).

**Comment by B4rb3rouss** [comment]
Ça fonctionne bien à première vue.
En effet, il faudrait modifier l'affichage, par exemple un menu ou un calendrier qui permette de naviguer parmi les dates de publication (plutôt que befor/after), ou simplement par tranche de 20 articles.
Mais je ne la ramène pas trop, car je ne sais pas faire :)

**Comment by remrem** [comment]
Cool ;)
Reste à définir les préférences (jour/calendar/nb d'articles)
@B4rb3rouss sisi, faut pas hésiter, tout avis et idée est à prendre en compte ;)

**Comment by BoboTiG** [comment]
D'ailleurs, si on garde les flêches :
- quand une flêche est non cliquable : opacité 50% et curseur `not-allowed` ?

**Comment by remrem** [comment]
@BoboTiG je pense que tu es plus familier du système de template que moi, j'ai pas envie de mettre les mains dedans pour l'instant, je laisse la main...

**Comment by BoboTiG** [comment]
Tu as fais des modifs niveau template admin ? que je sache si j'attends ton future commit.

**Comment by remrem** [comment]
Nop, tu peux y aller, je suis toujours sur les addons

**Comment by BoboTiG** [comment]
J'ai amélioré le comportement cat certains jours sont vides si on part sur le système journalier. Là, je suis parti sur le nombre d'éléments par page (par défaut 25, mais tout peut changer). Comme ça, pas de pages vides et, dans les préférences, on pourra sélectionner 10, 25, 50, 100, 300. Est-ce que vous avez besoin d'autres paliers dans ces nombres ?

**Comment by B4rb3rouss** [comment]
C'est très bien comme ça !

**Comment by BoboTiG** [comment]
C'est fait, ça va clairement plus vite ;)
