### ISSUE TITLE
Gestion des avatars

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/blogotext#146]
Je suis entrain de dédupliquer le code des avatars/favicons et ainsi n'avoir qu'une interface pour afficher un avatar partie admin et dans les thèmes.
Avez-vous une préférence pour le placement du fichier à appeler ?

Le dossier sera volatile dans `DIR_CACHE/avatars` et `DIR_CACHE/favicons`. Il y a une fonction commune `favatar()` qu'il suffit d'appeler et qui se charge de télécharger et afficher l'image.

Option 1 : est-ce qu'on crée un  fichier `/xxx.php` à la racine qui appelle ladite fonction ? Pour les images, il faudra appeler le script tel que :

    <img src="/xxx.php?options">

Option 2 : est-ce qu'on crée un dossier persistent `avatars` et on place un `index.php` dedans qui appelera ladite fonction ? Pour les images, il faudra appeler le script tel que :

    <img src="/avatars/?options">

Option 3 : une meilleure proposition ?

L'option 2 ne me botte pas plus que ça. J'aimerai que le dossier des avatars/favicons reste optionnel et supprimable au sein du dossier `DIR_CACHE`.

**Comment by B4rb3rouss** [comment]
La 1 paraît pas mal. Par contre, le xxx.php devra envoyer vers un dossier de cache d'avatars facile à supprimer qui n'est pas dans le même dossier que xxx.php.

**Comment by remrem** [comment]
la 1ère aussi

@B4rb3rouss 
> dossier de cache d'avatars facile à supprimer
ça arrive, depuis l'admin ;)

**Comment by BoboTiG** [comment]
Au final, concernant le cache, on aura :

    DIR_CACHE
        - avatars
        - favicons
        - cache flux

Pour le nom du fichier placé à la racine, on utilise le même nom que la faonction, càd `favatar.php` ?

**Comment by remrem** [comment]
`favatar.php`, hum, si ça gère aussi les favicons ... :/

**Comment by BoboTiG** [comment]
**fav**icon + f**avata** = favatar :)
Je suis open à toute suggestion hein.

**Comment by remrem** [comment]
ahhh ... mea culpa, je n'avais pas tilté ... du coup, pas de problème pour moi.
