### ISSUE TITLE
[LANG] Séparation admin/public

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#149]
L'idée est de soustraire des fichiers de lang de `/inc/lang/xx_xx.php` tout ce qui est utilisé par l'administration au profit de `/admin/inc/lang/xx_xx.php` (les noms et emplacements peuvent être modifiés).
L'objectif étant que la partie publique ne charge pas inutilement la partie admin et vis-versa.
Autre objectif possible serait d'autoriser les templates à avoir leurs propres fichiers lang (si besoin) (je ne sais pas si le fonctionnement actuel le permet, je pense que oui).

J'ai commencé à bosser là dessus : 
- `/inc/lang.php` à sauté aux profits de 2 fonctions (d'autres fonctions probablement à venir)
- copie de `/inc/lang/xx_xx.php` vers `/admin/inc/lang/xx_xx.php`
- début de nettoyage de `/inc/lang/xx_xx.php`

On adopte ? on laisse tomber ? on vise la 3.7 ou la 4.0 ?

**Comment by BoboTiG** [comment]
On adopte. Fais gaffe, j'ai poussé des MàJ pour ces fichiers.

**Comment by BoboTiG** [comment]
Yep !

**Comment by BoboTiG** [comment]
On est good sur celle-là, je peux fermer ou tu vois d'autres modifs à apporter ?

**Comment by remrem** [comment]
On peux cloturer, mais il faudrait créer un issue pour la roadmap 4.0
