### ISSUE TITLE
Sécurité des dossiers

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/blogotext#150]
Je viens de me rendre compte que lorsqu'on utilise l'option `recursive` de `create_folder()`, le fichier de proctection `index.php` n'est créé que dans le dernier sous-dossier. Le point poisitif, c'est que cette fonction n'est utilisée que dans les `addons`, on peut donc :
1. soit créer une nouvelle fonction `create_folder_recursive()` ;
2. soit modifier la fonction `create_folder()` pour qu'elle prenne en premier argument un `mixed` qui serait soit un tableau de dossiers à créer, soit une chaîne de caratères, comme ça l'est actuellement.

**Comment by remrem** [comment]
Suis plus favorable à la 2, mais pas trop chaud pour le mixed.

Quand j'ai ajouté l'arguments récursif, j'y ai pensé à ce problème de 'index.html', et je me suis dis qu'il faudrait tester tous les sous répertoire à la recherche d'un `index.html` ou `index.php` et si non présents, mettre un `index.html`, je ne sais pas pourquoi je ne l'ai pas fait :/

Et pour le `.htaccess`, inutile non ?

**Comment by BoboTiG** [comment]
On peut le laisser, il y a bien un moment où il servira, et puis mieux deux protections.

**Comment by remrem** [comment]
ça me parait résolu avec les modifications apportés par le PR #158 , Je pense que tu peux tester/confirmer et cloturer cette issue ;)
