### ISSUE TITLE
Cache: change for a complete independant cache folder

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/blogotext#152]
Il y a deux dossiers *cache* :
1. `var/cache` pour stocker les favicons (`var/cache/favisons`) et les avatars (`var/cache/avatars`). Il s'agit d'un cache *général* pour tous les domaines => gains de place et de requêtes.
2. `var/domain.tld/cache` pour stocker les flux RSS/Atom car chaque domaine à son propre contenu et les addons pourront y accéder pour leurs propres données.

**Comment by remrem** [comment]
J'ai quelques modifs à faire au `boot.php`, je m'en occupe.
```
    // we can break cache safely for 3.7, it's just cache
    define('DIR_CACHE', DIR_VAR.'/cache/');
    define('DIR_VHOST_CACHE', DIR_VHOST.'cache/');
```

**Comment by BoboTiG** [comment]
Je pense qu'on est bon sur celle-ci, tu peux confirmer @remrem ?

**Comment by remrem** [comment]
ça me semble bon, pour la suite, ça relèvera du bug, donc nouvelle issue ;)
