### ISSUE TITLE
[rules][addon] conventions

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#156]
1. forcer une convention sur le nommage des fonctions au sein d'un addon,  genre `a_{tag}_*` histoire d'éviter d'avoir des fonctions avec le même nom addon1<->addon2 et addon<->core
2. points de vue `$declaration`, je pense qu'il faut obliger à déclarer au minimum : 
```
$declaration['tag']
$declaration['name']['en']
$declaration['desc']['en']
$declaration['version']
$declaration['compliancy']
```
3. pas de code, variable (...) hormis `$declaration` qui soit en dehors des fonctions / classes
4. _indication de licence, `$declaration['licence']` ?_ On considère que les addons héritent de la licence utilisée par BT

**Comment by BoboTiG** [comment]
Les nom et description ne devraient pas être obligatoire dans toutes les langues, si ? Au moins en en anglais. Et s'il manque une trad, on fallback sur l'anglais.

La licence, si je ne me trompe pas, ne peut pas être différente de celle de BT, donc pas besoin de l'ajouter explicitement.

**Comment by remrem** [comment]
Ok pour les langues.
Ok pour les licences, pour reprendre ce que dit [wordpress.org > license](https://wordpress.org/about/license/)

> There is some legal grey area regarding what is considered a derivative work, but we feel strongly that plugins and themes are derivative work and thus inherit the GPL license. If you disagree, you might want to consider a non-GPL platform such as Serendipity (BSD license) or Habari (Apache license) instead.

**Comment by remrem** [comment]
Concernant la 1., soit on change le nom des fonctions dans la partie core, soit au niveau des addons, parce qu'actuellement, addons et core utilisent addon(s)_.
le risque de collision est faible du a l'utilisation de `_{tag}_*` dans les addons, mais il existe.
@BoboTiG , tu tranches ?

**Comment by BoboTiG** [comment]
Sachant qu'il n'y a qu'une seule fonction qui doit suivre un schéma de nommage pour chaque addon, on peut rester sur ta proposition `_{tag}_*`, voire `_addon_{tag}_`. Choisis ce que tu préfères.

**Comment by remrem** [comment]
Le propos est de forcer toutes les fonctions qu'un addon peux avoir (fonctions de hook, de bouton et de tag) à utiliser `a_{tag}_*`

**Comment by BoboTiG** [comment]
Forcer la main sur toutes les fonctions, ça risque d'être lourd pour les développeurs, non ?

**Comment by remrem** [comment]
Pas aussi lourd pour eux, que pour nous et que pour l'utilisateur en cas de conflit de function ;)
Et c'est pas la mère à boire...

**Comment by BoboTiG** [comment]
Autre solution, une seule fonction qui contient les autres ? Trop sale ? Trop privatif ?

**Comment by remrem** [comment]
pas fan des fonctions imbriquée dans d'autres fonctions... hormis pour des petites choses je pense que c'est à éviter dans la mesure du possible.

**Comment by BoboTiG** [comment]
Tout à fait d'accord. OK pour ta solution.

-- 
Mickaël Schoentgen
http://www.tiger-222.fr

**Comment by BoboTiG** [comment]
Je peux fermer celle-ci ? Partis comme nous sommes, les addons ne devraient pas énormément bouger.

**Comment by remrem** [comment]
Yep, je pense qu'on est bon là dessus, juste à documenter tout ça sur le wiki et le plugin exemple
