### ISSUE TITLE
[VHOST] besoin de vos cellules grises...

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#159]
à propos de  `secure_host_to_path()` , il y a un risque de collisions dans les vhosts : 
- Ok, résolu par @BoboTiG (on garde les ".")     
_`http://blog.example.tld` & `http://blog-example.tld` > `blog.example.tld` & `blog-example.tld`_   
- Toujours pas résolu    
`http://example.tld/~tom/` = `http://example.tld/-tom/` > `example.tld--tom`

_Proposition : ajouter un bout de md5 de l'url à la fin, on garde le côté "lisible" du vhost et on réduit le risque de collision :
`example_tld--tom` -> `example_tld--tom_4d68e`_ On n'utilise pas de hash.

Qu'en pensez-vous ? des idées ?

**upd** édit, avec solutions

**Comment by BoboTiG** [comment]
Et si on garde les points du nom de domaine, ça va pas ? 

- `http://blog.example.tld` = `http://blog-example.tld` >
>`blog.example.tld`   
>- `http://example.tld/~tom/` = `http://example.tld/-tom/` >
>`example.tld-tom`

J'avais prévu de faire la remarque. Les points ne sont pas dangereux en soi, et c'est même plus lisible/compréhensible.

-- 
Mickaël Schoentgen
http://www.tiger-222.fr

**Comment by remrem** [comment]
Yep, mais je suis pas fan d'avoir des dossier qui se nomme comme des fichiers toto.com ... :/ et vu que les tld partent en vrille point de vue ouverture ... là, pas de confusion, de risques ...

**Comment by BoboTiG** [comment]
Je n'aime pas ajouter un hash MD5 en plus (niveau performances et nom pas sexy). Sinon,  on supprime les points du NDD (nom de domaine). Propre: "exampleorg-blog".

-- 
Mickaël Schoentgen
http://www.tiger-222.fr

**Comment by remrem** [comment]
pour supprimer les points, ça ne fonctionne pas : 
http://toto.example.com = totoexample.com > `totoexamplecom`
pour le md5, ça me paraissait la bonne solution, au moins c'est un peu de sécurité en plus, du md5 n'est pas lourd comme méthode de hash (pt de vue calcul, d'autant plus pour un petit string) et en ne gardant que 5-6 chars en fin, on de "défigurer" pas trop... :/

**Comment by remrem** [comment]
Vu avec @BoboTiG, on conserve les points.

**Comment by BoboTiG** [comment]
Je ferme celle-ci @remrem, à moins que tu vois autre choses à ajouter ?

**Comment by remrem** [comment]
Hormis : 
`http://example.tld/~tom/` = `http://example.tld/-tom/` >`example.tld-tom`
Je pense que l'on peu fermer, vu le peu de risque de tomber sur ce cas... et je pense qu'on limitera encore les collisions lors des procédures d'installations de la v4

**Comment by BoboTiG** [comment]
Faudra tout de même le faire, mon install est dans un sous-sous-sous dossier ^^ 
Il est fréquent de trouver des install dans `domain.tld/(blog|news)`.

**Comment by remrem** [comment]
les sous dossier ne sont pas un problème, les sous-sousousousous dossier devrait passer aussi (à vérifier), ce qui me pose problème ce sont les tilde example.com/**~**toto/

**Comment by BoboTiG** [comment]
Ah OK. Un str_replace devrait suffire.

-- 
Mickaël Schoentgen
http://www.tiger-222.fr

**Comment by remrem** [comment]
oui, mais on remplace par quoi ?
sachant que `/_toto/` `/-toto/`

**Comment by BoboTiG** [comment]
Après avoir lu par-ci, par-là,  on peut carrément garder le caractère. Il est valable sur les systèmes Unix, GNU/Linux et Windows.

Le remplacer paf n'importe quel caractère ferait une collision tôt ou tard.

-- 
Mickaël Schoentgen
http://www.tiger-222.fr

**Comment by remrem** [comment]
Ok. je modifie le script et on pourra cloturer ce ticket

**Comment by remrem** [comment]
Je pousse avec mon prochain PR ;)
