### ISSUE TITLE
[ADMIN] index.php

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#163]
J'ai un commit qui arrive, c'est juste pour laisser une trace propre aux modifications et en cas de bug suite à mes modifications...
- mets des graphes sur 96 mois par défaut (pas terrible à l'install ou blog "jeune")
- pas optimisé, requêtes SQL inutiles ...

**upd** @BoboTiG , tu peux mettre dans la roadmap 3.7 ?

**Comment by remrem** [comment]
Refactoring de `/admin/index.php`, à tester/valider sous différents navigateur + base de données (en jouant sur les dates des articles)

**Comment by BoboTiG** [comment]
Je viens de tester et il y a deux petites erreurs s'il n'y a pas de données (0 commentaire, par exemple).
J'envoie un patch.

**Comment by remrem** [comment]
... My bad, je n'ai pas testé/prévu ce cas de figure ... :/

**Comment by BoboTiG** [comment]
cf 7c31ebf0d566355cd8bcd6fe488244b638ae8778

**Comment by BoboTiG** [comment]
Par contre, j'aime bien la présentation plus légère :)

**Comment by remrem** [comment]
yep, j'ai laissé au max 96 mois, mais en terme de stats, je trouve ça trop lourd, on peux sans doute revoir le max à 12/24 mois... non ? (ligne 53, `$show_max = 96;`)

**Comment by BoboTiG** [comment]
24 c'est pas mal, comme ça tu peux voir les stats de l'année en cours et celles de l'année passée.

**Comment by remrem** [comment]
Yep... Je cloture, pour ce genre du détail, c'est du cosmétique qui dépend d'une variable, on peux voir ça durant le freeze (ou faire ça avant...)
