### ISSUE TITLE
[CORE] Meilleure gestion des erreurs (fichier log)

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/blogotext#164]
**UP** J'ai viré les chemins complets.

Actuellement, on a ces lignes dans le fichier log :

    [29-Nov-2016 12:20:21 UTC] addon calendar fail on name test BlogText v:3.7.0-dev in file "/mnt/master/www/local/blogotext/index.php" on line 20

La ligne 20 du fichier `index.php` est `addons_init_public();`. En regardant de plus près le contenu de `debug_backtrace()`, on peut fournir quelque chose de plus complet, parce que ladite fonction fait 50 ligne et appelle elle-même 7 autres fonctions.

Proposition :

    [29-Nov-2016 12:50:21 UTC] [BlogoText 3.7.0-dev] addon calendar fail on name test
    Stack trace:
        -> addons_init_public() called at [index.php:20]
        -> addon_load() called at [inc/addons.php:167]
        -> addon_test_declaration() called at [inc/addons.php:397]

Qu'en dites-vous ?

**Comment by remrem** [comment]
ça dépend, on utilise cette fonction pour dev ou prod ? en prod, ça peux être vite pourrir les logs d'être trop bavard (c'est pour ça que j'avais proposé d'utiliser des level (warn, debug ...)

**Comment by BoboTiG** [comment]
J'en suis là. En dev:

    [2016-11-29 20:15:54 UTC, v3.7.0-dev] addon calendar fail on name test
    Stack trace:
        -> addons_init_public() called at [index.php:20]
        -> addon_load() called at [inc/addons.php:167]
        -> addon_test_declaration() called at [inc/addons.php:397]
    [2016-11-29 20:15:54 UTC, v3.7.0-dev] addon require a name (at least in english) (calendar)
    Stack trace:
        -> addons_init_public() called at [index.php:20]
        -> addon_load() called at [inc/addons.php:167]

En prod:

    [2016-11-29 20:16:46 UTC, v3.7.0-dev] addon calendar fail on name test at [inc/addons.php:332]
    [2016-11-29 20:16:46 UTC, v3.7.0-dev] addon require a name (at least in english) (calendar) at [inc/addons.php:399]

C'est clair, concis et en dev comme en prod, on saura exactement d'où vient l'erreur. Verdict ?

**Comment by remrem** [comment]
ça me parait vraiment pas mal :D 
suggestion, se baser sur la contante DEBUG ?

**Comment by BoboTiG** [comment]
Exactement, en gros:

    function log_error($message, $write = true)
    {
        if ($write === true) {
            $log = $message_formaté;
            if (DEBUG) {
                $log .= $stacktrace;
            }

            error_log(addslashes($log)."\n", 3, BT_ROOT.'var/php-error.log');
        }
    }

**Comment by remrem** [comment]
Simple et efficache ;)
un petit logrotate maison sur le nom du fichier, un dossier /var/log/ et je pense qu'on est bon :D

**Comment by remrem** [comment]
et il y a la constante `DIR_VAR` qui tape directement dans `BT_ROOT.'var/'`

**Comment by BoboTiG** [comment]
Normalement, je ne casse rien avec ce commit.

**Comment by remrem** [comment]
Tu clotures trop vite... Pressé de passer en freeze ? :D
Cf. plus haut mon commentaire : 

> un petit logrotate maison sur le nom du fichier, un dossier /var/log/ et je pense qu'on est bon :D

**Comment by BoboTiG** [comment]
Je n'avais pas saisi que tu voulais implémenter un logrotate nous-mêmes. Est-ce réellement nécessaire ? Il s'agit d'un fichier qui aidera les développeurs d'addon, pas besoin de sortir l'artillerie lourde :)

**Comment by remrem** [comment]
Je pense au long terme, ça va pas le faire d'avoir des utilisateurs qui viennent râler parce que leur fichier log fait plus de 10Mo (Loi de Murphy), avec un logrotate on peux nettoyer plus facilement (v4 feature inside ?). Et si on demande un extrait du log pour faire du debug, si les mecs nous envoient des pavés de X mo, ça va vite être lourd... 
Et moi, ça me permet de dev mon outils de monitoring/stats pour ma ferme à côté sans devoir parser des fichiers de fou ... ^^

**Comment by BoboTiG** [comment]
Il y a trop d'implication personnelle là ! :)
Un lgrotate journalier tout simple (on définit la date courante dans le nom du fichier), ou comment vois-tu le bousin ?

**Comment by remrem** [comment]
yep, par jour, dans /var/log/ et c'est marre ;)

**Comment by BoboTiG** [comment]
OK, je m'en charge. Du coup, ça allègera le contenu étant donné que la date ne sera plus nécessaire.

**Comment by BoboTiG** [comment]
`/var/log/errors-20161130.log` ça te va ?

**Comment by remrem** [comment]
yep, nickel ;)
