### ISSUE TITLE
[CORE] admin/feed

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#165]
Je viens de jeter un coup d’œil sur le lecteur de feed intégré dans la partie admin.
**Bug**
1- semble ne pas se rafraîchir correctement lors de l'utilisation de MySQL (en SQLite pas de pb constaté) (je suis dessus)

**A revoir** 
2- optimisation de la bdd
3- chargement des favicon, bloque le chargement de la page. (je suis dessus)

**Optimisations**
4- mutualiser les sources/refresh entre les vhosts ?
5- en cas de ferme, une option pour l'admin de la ferme pour empêcher le refresh par un rédacteur si l'admin mets en place un cron ?

**Comment by BoboTiG** [comment]
C'est la syntace du `LIMIT` qui coince avec MySQL ?

Mutualiser les ressources entres les vhosts ? Non, laissons chacun son petit endroit privé :)
Et c'est mieux de ne pas bloquer l'utilisateur, s'il veut faire fumer son serveur, libre à lui.

**Comment by remrem** [comment]
My bad, c'est pour rafraîchir les flux (insert en db), le compteur des feed incrémente bien au fur et à mesure qu'il parcourt les feed à rafraichir mais la plupart des flux n'ont pas l'air d'être insérés en bdd ... Je n'ai pas regardé plus que ça.

pour la mutualisation, je parle juste du rafraîchissement des feed, si 50 blogs qui consultent le même feed, c'est dommage de devoir rafraîchir 50 fois auprès de la même source :/

**Comment by remrem** [comment]
je vais essayer de trouver ce qui déconne pour les insert cet après-midi.

**Comment by remrem** [comment]
J'ai trouvé les quelques problèmes qui bloquent les inserts en bdd , je pousse plus loin pour peaufiner....
- Problème de conception (text -> mediumtext) dans la table (rss)
- ne supporte pas certains emoji, j'ai réglé ça avec une regex, faute de mieux
- retourne des erreurs sur les flux rss mal formaté/incomplet (http://blog.z3bra.org/rss/feed.xml), je pallie en complétant au mieux.

Le fonctionnement n'est pas optimisé, je vois pour faire au mieux sans tout retourner ...

**Comment by remrem** [comment]
Pour faire le topo : 
1- ça semble réglé
2- Je n'y touche pas
3- réglé
4- rejeté
5- rejeté
Je cloture
