### ISSUE TITLE
[ADMIN] feed.php mauvais comportement

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#172]
Mauvais comportement dans /admin/feed.php : 
- Si on sélectionne un flux particulier dans la colonne de gauche, ça ne fait le tri que sur les X éléments affichés par la page, si il n'y a pas d’élément du flux dans la page, ça n'affiche rien.
- Si on sélectionne un flux, et que l'on souhaite afficher les éléments précédents en cliquant sur "<" ou ">", ça affiche les X éléments, mais de tout les flux.

Solution proposée :
à chaque clique sur ">", "<", flux (colonne gauche) on récupère la liste qui va bien en json via une requête http, ça implique de modifier le JS de `/admin/feed.php` et de revoir le fonctionnement des requêtes SQL.

**Comment by remrem** [comment]
je suis dessus.

**Comment by remrem** [comment]
PR #172, je pense que c'est bon, par contre le JS est passé à la trappe :/

**Comment by BoboTiG** [comment]
> par contre le JS est passé à la trappe

Comment ça ?

**Comment by remrem** [comment]
Ce n'est plus dynamique (rechargement de la page)

**Comment by remrem** [comment]
Si c'est bon pour toi, tu peux clôturer.

**Comment by BoboTiG** [comment]
Je vais m'occuper du JS, et ça sera good.

**Comment by remrem** [comment]
^^
