### ISSUE TITLE
Addons: text option invalid behavior

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/blogotext#185]
La configuration de l'addon `plugin_example`, par exemple : cliquer sur **Enregistrer** plusieurs fois. Le contenu de la variable `label pour text` est modifiée de façon inattendue.

**Comment by remrem** [comment]
Je viens de jeter un coup d'oeil, ça devrait être bon avec le pr #186

**Comment by BoboTiG** [comment]
Nickel !
