### ISSUE TITLE
Admin : graphics on small screens

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/blogotext#189]
Il faut revoir à la baisse le nombre de mois affichés sur petit écran.

**Comment by remrem** [comment]
pr 190, ne réduis pas le nombre de mois, affiche juste Xn+1.
Quick fix ... Si ça te va ...

**Comment by BoboTiG** [comment]
Je viens de tester et ça fonctionne partiellement.
Le nombre de mois est bien réduis, mais le nombre de points sur le graph ne l'est pas. Tu vois ce que je veux dire ?

**Comment by BoboTiG** [comment]
Je m'en occupe, on va récupérer le système mis en place par Timo, ingénieux.

**Comment by remrem** [comment]
#191 j'ai ajouté la détection des mobiles via l'user agent, du coup ça réduit le nombre de colonnes.
Se sont juste des données de "complaisance", pas envie de me prendre la tête avec ça, d'autant plus que pour la v4 on pourrait surement trouver plus utile à afficher... (?)

**Comment by remrem** [comment]
@BoboTiG, tu t'en occupe ou je bricole un truc (autre que le PR #191) ?

**Comment by BoboTiG** [comment]
Si tu peux bricoler un truc autrement, quelque chose de plus générique qui s'adapte aux dimensions de l'écran, ça serait assez génial :)

**Comment by remrem** [comment]
Ok. J'essaie de voir ça demain.

**Comment by remrem** [comment]
Cf. PR #212 , en gros : chaque mois fais au minimum 40px  (JS) et ce qui sort du graph est caché (CSS)
J'ai conservé l'affichage alterné des noms des mois, histoire de garder en clarté ...

**Comment by remrem** [comment]
Good to close ?
