### ISSUE TITLE
facebook sharing, blogotext et les images

### ISSUE THREAD

**Issue by graffx27** [BoboTiG/blogotext#192]
Salut à tous, je ne sais pas trop si c'est le bon endroit pour parler de ce soucis avec la communauté blogotext, j'ai du mal à comprendre ce site (github).

J'ai installé des boutons facebook pour partager mes articles. Oui, quelle horreur je suis d'accord, m'enfin bref.

Tout fonctionne très bien, sauf si j'ajoute des photos dans les articles.
Je m'explique, sans photo dans un article, si je le partage, la photo qui apparaitra sur facebook est bien celle que j'ai choisi (og:image dans le <head>). En revanche, dés que je pose une ou plusieurs photos dans un article, l'une d'elle remplace systematiquement celle choisie lors du partage.

Je me tire les cheveux depuis des jours avec le debuggeur facebook, et j'en conclue que pour une raison qui m'est inconnue, le probleme vient de blogotext, ayant le même systeme de partage sur un pluxml, un wordpress et un site codé de A à Z.

Mais alors la question, c'est pourquoi????

Je ne comprend rien de rien et je suis condamné à ne pas mettre d'image dans mes articles car je tiens absolument à avoir comme image le logo de mon site et rien d'autre.

Bon je sais, c'est pas vraiment une priorité pour vous et je le comprend, docn même si personne ne cherche ou ne trouve, aucun souci :)

Je suis juste étoné de ne voir personne avec le même problème.

En tout cas, BONE ANNEE A TOUS :)

**Comment by remrem** [comment]
Tu as une URL à proposer pour que je puisse jeter un coup d'oeil (partie publique) ?

**Comment by graffx27** [comment]
Ho bien sur, je m'attendais pas a une reponse si rapide ^^

http://   mickaelpiot  .  fr

**Comment by graffx27** [comment]
par exemple celui-i est accompagné d'une capture d'écran de sa cagnotte, ca ne veut plus rien dire sans image :(

http://   mickaelpiot    .   fr/?d=2016/12/22/15/09/39-agoraphobe-matt-a-besoin-de-vous-mise-a-jour

**Comment by remrem** [comment]
Pour `http://mickaelpiot.fr?d=2016/12/22/15/09/39-agoraphobe-matt-a-besoin-de-vous-mise-a-jour`
- vérifie l'url de ton image : `http://mickaelpiot.fr/img/36/image3333.png`,ça renvoie un 404 (non trouvé)
- ton `<meta property="og:image" content="themes/default/logo.png">` pointe vers ton logo de blog, c'est bien ce que tu souhaites ?
- tu dois avoir un problème quelque par dans le javascript (fb ?) le DOM est manipulé par un script JS et ça pourrit littéralement le dom de ta page :/

**Comment by graffx27** [comment]
Merci de ton interet à mon soucis:

- cette image 3333.png, tu vois ca ou exactement?

- Oui, ca pointe bien vers logo.png pour le og:image

- la ca dépasse mes compétences, je vois ce qu'est le DOM, je vois ce qu'est un script js (j'en utilise quelques fois) mais que le JS puisse  confluer le DOM, la je comprend pas :o

**Comment by graffx27** [comment]
Les 3 seuls JS que j'ai, sont pour les boutons facebook, pour convertir les smileys-textes en smileys-images, et une banniere adblock, le reste est au naturel :/

**Comment by remrem** [comment]
Pour `http://mickaelpiot.fr?d=2016/12/22/15/09/39-agoraphobe-matt-a-besoin-de-vous-mise-a-jour`

- `/img/36/image3333.png` est dans le contenu de l'article apparemment.

j'essaie de cibler ton problème de JS, mais avec ublock et ghostery, je bloque tout ce qui est lié à fb et adsense, et là, ta page s'affiche correctement.

pour info : 
https://framadrop.org/r/lNe1X01SJ-#sIaoqcaYGO8jCU+Db7SKxFXT6rmbXjYMy0LROfN+/Ow=
https://framadrop.org/r/0TywbF3h47#MwMH9UquWNglJ5K1hAU/wpc/ZtRolJHQtyfXqsrpCMk=

**Comment by remrem** [comment]
Quand tu inclus les scripts de fb et d'adsense, ceux-ci accède au dom de ta page pour le modifier, par exemple le script de fb : 
```
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.8&appId=xxxxxxxxx";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
```
va parcourir le DOM à la recherche du premier `<script>` qu'il va trouvé et va insérer des `<script src=""...` juste avant, il va aussi, par le biais des scripts qu'il appéle modifier le contenu de `<div id="fb-root"></div>`. C'est à peu prés le même fonctionnement pour adsense.

Autre chose, dans ton `<head>`, veille à bien fermer les balises ` />`, ce n'est pas le cas pour quasiment toutes tes balises `og:`.

Vérifie ton fichier html de template, apparemment tu as un caractères avant le `<!DOCTYPE html>` ça peux aussi causer des problèmes.

Tu utilises quoi pour éditer ton template ?

**Comment by graffx27** [comment]
Merci, je vais corriger, par contre il n'y a que la balise og:image que j'ai oublié de cloturer effectivement, les autres sont bien fermées;

Je vais vérifier si j'ai un BOM en début de page comme tu me le dis, etrange il serait donc la avant téléchargement de blogotext :/

Pour l'éditeur, j'utilise celui interne a blogotext :/

**Comment by remrem** [comment]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fmickaelpiot.fr%3Fd%3D2016%2F12%2F22%2F15%2F09%2F39-agoraphobe-matt-a-besoin-de-vous-mise-a-jour

je vais vérifier le template, mais je n'ai pas encore eu ce problème avec BT.

Pour l'éditeur, je parle pour modifier ton template, genre notepad.

Pour info, la version 3.7 ne va tarder à pointer le bout de son nez (question de jours), il y aura un système d'addon et les addons qui vont bien pour le partage sur les réseaux sociaux sont prévus ;) (pour adsense, c'est envisageable)

**Comment by graffx27** [comment]
Super si y'a une nouvelle version! Alors   

- j'utilise dreamwaver et chose bizarre, effectivement il y avait un BOM, chose incompréhensible puisque ma config les supprime automatiquement d'habitude.

- j'ai fermé la balise og:image mal espacée.

le probleme a l'air corrigé aux premiers abords, je fais quelques tests et te tient au courant :)

Merci encore pour le temps passé avec moi!

**Comment by remrem** [comment]
Pour le format de fichier (je ne connais pas suffisament dreamwaver), mais il vaux mieux utiliser `UTF-8 without BOM`, mais bon, "Shit happens" ;D

Cool, pas de problème, n'hésite pas ;)
Bon réveillon ;)

**Comment by graffx27** [comment]
Merci à toi aussi!

En passant, ca semble résolu pour facebook, par contre maintenant c'est google+ qui prend les images des articles au lieu de celle mentionnée avec itemprop :


```
	<meta property="og:image" content="themes/default/logo.png" />
	<meta itemprop="image" content="themes/default/logo.png" /> 
```

XD

**Comment by remrem** [comment]
Peut-être est-ce du au fait que le template par défaut utilise les microdata (schema.org), essaye de les virer du template  (`itemprop`, `itemscope`, `itemtype `...)

https://developers.google.com/+/web/snippet/

**Comment by graffx27** [comment]
Desolé, reveillon fait mal au crane lel.

J'ai essayé, ca me supprime le design en background, je teste demain aprés avoir cuvé et je te redis, bonne année à toi :)

**Comment by BoboTiG** [comment]
Puis-je fermer cette issue ?

**Comment by graffx27** [comment]
Bonjour, desolé, on peut fermer, facebook restera toujours une usine à gaz :)

**Comment by remrem** [comment]
@graffx27 , attends la 3.7 et les addons qui vont bien, ça ne va pas tarder et t'épargner des maux de têtes (ainsi qu'à moi ;))
