### ISSUE TITLE
Il y a une galerie photo de prévue ?

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#214]
Je me posais la question depuis quelques temps, pourquoi, dans l'ajout de fichier (dans l'admin), a-t'on un formulaire pour un nom, desciption, album (...) ?

En fouillant un peu, je pense avoir trouvé un début de réponse sur 
https://lehollandaisvolant.net?d=2015/08/29/19/15/11-sortie-de-blogotext-30#idbacc7c

ça remonte un peu ~~, et point de vue code / interface, à part ce formulaire, je ne trouve pas plus de chose qui suggère la présence d'une galerie ...~~

Du coup ? A faire ? A virer/dégrader ? Pas touche ?
Besoin d'une galerie photo côté publique ?

**UPD** après avoir fouiné dans le code, les "albums" servent aussi dans l'affichage de l'administration. Du coup, le fonctionnement est comparable au tag ... non ?

**Comment by B4rb3rouss** [comment]
À retirer ?
Un addon qui fait ça bien appelé **si** besoin paraît plus judicieux.

Au passage, pour les images, un bout qui optimise les images pour limiter le chargement serait plus utile, mais c'est un autre sujet.

**Comment by remrem** [comment]
> Un addon qui fait ça bien appelé si besoin paraît plus judicieux

Je suis du même avis, mais je ne vois pas trop comment gérer ça point de vue administration sans ouvrir plus l'interface administrateur aux addons (je sais pas si je suis suffisamment clair sur celle là :D)

> Au passage, pour les images, un bout qui optimise les images pour limiter le chargement serait plus utile, mais c'est un autre sujet.

point de vue admin ? je revois un peux les choses, j'essaie de faire une interface un peu plus fonctionnelle.

**Comment by B4rb3rouss** [comment]
> Je suis du même avis, mais je ne vois pas trop comment gérer ça point de vue administration sans ouvrir plus l'interface administrateur aux addons (je sais pas si je suis suffisamment clair sur celle là :D)

Dans le doute, autant demander aux utilisateurs lors de la sortie de la 3.7. Pour ma part, si j'ai besoin de ça, j'installe le bout de CSS qui va bien à la main. En passant, ça peut se faire sans JS : http://youmightnotneedjs.com/#image_slider

> point de vue admin ? je revois un peux les choses, j'essaie de faire une interface un peu plus fonctionnelle.

J'avais en tête une case à cocher dans le formulaire d'upload d'images qui propose d'optimiser l'image (avec php-gd) et avoir un jpg progressif par exemple.

**Comment by remrem** [comment]
> J'avais en tête une case à cocher dans le formulaire d'upload d'images qui propose d'optimiser l'image (avec php-gd) et avoir un jpg progressif par exemple.

ahhh ... my bad ... j'avais compris de travers (l'optimisation de l'UI pour l'affichage des images dans l’administration) :D 
Pourquoi pas... à voir avec @BoboTiG :D

**Comment by remrem** [comment]
après avoir fouiné dans le code, les "albums" servent dans l'affichage de l'administration. Du coup, le fonctionnement est comparable au tag ... non ?
