### ISSUE TITLE
J'ai plusieurs problèmes et questions

### ISSUE THREAD

**Issue by jejedu67** [BoboTiG/blogotext#218]
Bonsoir,

Je viens d'installer Blogotext mais j'ai plusieurs questions et problèmes:

1) https://mixmaster-online.fr/blog/index.php?liste#
Pourquoi est ce que l'article ne s'affiche pas "ouvert" comme chez le hollandais volant avec le contenu déjà visible sans clique ?
https://lehollandaisvolant.net/

2) Dans le réglages si je met mots clé méta automatiques et que j'enregistre, le changement n'est pas conservé.
http://prntscr.com/e8uhhp

3) https://mixmaster-online.fr/blog/index.php?liste#
Pourquoi est ce qu'il y a rien dans "Trouver un article" et "Liste de tags" ? J'ai un article et il possède des tags ...

4) On ne peut pas régler ce qui est affiché sur la page "A propos" via la partie admin, d'ailleurs la page existe pas.

Merci d'avance pour votre aide

**Comment by remrem** [comment]
Petit oubli de ma part, j'ai vu que tu utilises la 3.7.0-dev, les addons (calendar ...) ne sont plus intégrés par défaut, ils sont disponible sur https://github.com/BoboTiG/blogotext-addons, et à placer dans le dossier `addons`.

Si tu utilises la version `dev` en production, modifie dans `inc/boot.php` vers la ligne 25 :      
```define('DEBUG', true);``` par ```define('DEBUG', false);```

**Comment by jejedu67** [comment]
Bonjour,

Merci d'avoir répondu.

1) Effectivement je n'avais même pas pensé à retirer le ?liste 

2) Ah bon les moteurs de recherche ne s'en servent plus beaucoup, bon à savoir

3) En faite au début j'avais testé la version du hollandais volant (https://github.com/BoboTiG/blogotext) et dans les tags au bas des articles, lorsque j'appuyais sur la touche Entrer ça mettait le tags dans un genre de rectangle gris mais il restait bien sûr dans la ligne des tags de l'article puis en page d'accueil je le voyais justement  dans "Liste de tags". Maintenant avec cette version quand j'appuie sur Entrer ça enregistre l'article mais le tag n'est pas mit dans un "rectangle" gris dans la ligne des tags de l'article, ça reste comme ça: http://prntscr.com/e8za6k et je trouve pas comment régler ça. Je pense que le problème est lié que le tag n'est pas intégré dans un "rectangle gris" comme sur la version initiale de blogotext.

4) D'accord je vais faire ça. Ou alors créer une page où je mettrais un peu de texte et le lien vers les mentions légales du site (que je n'ai pas encore fais).

Pour le soucis de sous domaine, comme j'utilise Clouflare il fallait ajouter le nom du sous domaine et l'IP du serveur ce que je ne savais pas. Il faut attendre la propagation DNS à présent.

J'ai placé le calendrier mais les dates de publication des articles ne sont pas entourées dessus.

Et j'ai modifié DEBUG à false.

**Comment by jejedu67** [comment]
Petite précision. Les liens du calendrier sont bien cliquables, mais pas entourées.
Si je modifie dans le CSS ça se répercute sur tout le blog:
http://prntscr.com/e8zji3

**Comment by remrem** [comment]
Il faut bien faire la distinction entre les keywords (de la balise meta) et les catégories/tags, je sais, point de vue lexique, c'est pas au point pour l'instant :/
Dans les préférences, active `Classement des billets par catégories` pour jouer avec les tags/catégories     
et active `Mots-clés meta automatiques` pour que BT gère la balise meta keywords à ta place.

Pour le template / calendar, je jette un coup d'oeil.

**Comment by remrem** [comment]
Pour la modification de thème, je te conseille de faire une copie du thème par default, de le renommer (sans espace/caractères spéciaux) et d'utiliser/modifier ta copie, ainsi, lors des prochaines mises à jours de blogotext, ton thème ne sera pas écrasé. (ne pas oublier de choisir ton thème dans admin > préférences)

Pour modifier l'apparence de l'addon calendar, je te conseille de le faire dans le fichier css de ton thème (et non pas de l'addon), par exemple, en fin du fichier css, tu peux ajouter : 
```
#calendar td a{
    background-color: #dadada;
    border-radius: 50px;
}
```

Mais dans l'état actuel, avec ton problème de config et de dns, le fichier CSS de l'addon n'est pas chargé correctement (ça demande `https://blog.mixmaster-online.fr/addons/calendar/style.css`).

En attendant la propagation DNS, tu ne peux pas configurer BT pour utiliser `https://mixmaster-online.fr/blog/` (qui a l'air fonctionnel) et après le basculer sur `https://blog.mixmaster-online.fr/` (qui semble être ton objectif final) ?

**Comment by jejedu67** [comment]
Ah mince je définissais un mot clé et non un tag au bas de l'article. Là ça va mieux :)

Donc tout est réglé sauf le réglage du sous domaine. Bon ça c'est mon problème. Ce n'est pas urgent je vais laisser ça ainsi.

Merci de votre aide
Bonne après midi

**Comment by remrem** [comment]
Pas de problème, n'hésite pas en cas de besoin.
Si c'est tout bon pour toi, peux-tu clôturer cette issue ?

**Comment by jejedu67** [comment]
Bonjour,

Oui je clôture.

Encore merci :)
