### ISSUE TITLE
sauts de lignes

### ISSUE THREAD

**Issue by graffx27** [BoboTiG/blogotext#222]
Salut à la communauté!

y'a t-il un moyen de respecter les sauts de ligne comme on l'entend?

Par exemple, entre 2 phrases si je veux mettre 3 sauts de ligne, il n' y en aura toujours qu'un à la lecture par défaut.

J'ai tenté de modifier conv.php mais aucun changement sur mes articles.

merci d'avance!

**Comment by remrem** [comment]
Dans ton article, tu peux mettre 2 ou 3 espaces dans les lignes vides.
```
Test
  
  
  
Test
```

**Comment by remrem** [comment]
@graffx27 , ma réponse a-t-elle solutionné ton problème ?

**Comment by graffx27** [comment]
Bonjour,

ca n'a pas résolu mais rès bien dépanné, merci pour l'info, il fallait le savoir! 👍
