### ISSUE TITLE
[RSS] commande cron ne marche pas

### ISSUE THREAD

**Issue by B4rb3rouss** [BoboTiG/blogotext#227]
La ligne cron proposée pour mettre à jour les flux RSS ne semble pas fonctionner.
Enfin c'est la commande qui ne va pas, rien à voir avec cron.

À confirmer.

**Comment by B4rb3rouss** [comment]
Non, il y a bien un souci même en ajustant la ligne cron.
C'est tout bête, mais wget est redirigé vers la page de login visiblement d'après les logs

**Comment by B4rb3rouss** [comment]
wget est renvoyé vers la page de login pour l'admin d'après les logs.

```
test.yeuxdelibad.net 109.190.193.124 - - [15/Mar/2017:22:28:01 +0100] "HEAD /blog/admin/_rss.ajax.php?guid=779d847397da640207e40107c9d76bcd7676f224%26refresh_all HTTP/1.1" 302 0 "" "Wget/1.18 (openbsd6.0)"
test.yeuxdelibad.net 109.190.193.124 - - [15/Mar/2017:22:28:02 +0100] "HEAD /blog/admin/auth.php HTTP/1.1" 200 0 "" "Wget/1.18 (openbsd6.0)"

```

**Comment by remrem** [comment]
Ok, Si tu veux je peux me pencher là dessus demain.

**Comment by remrem** [comment]
Ok, j'ai trouvé le problème : il n'y a pas d'exception pour le cron en ce qui concerne les processus d'identification.
J'ajoute une exception avec quelques sécurités et je PR tout à l'heure.

**Comment by remrem** [comment]
le PR #228 doit régler le problème.
Si tu peux tester de ton côté.

**Comment by B4rb3rouss** [comment]
wget accède désormais à la page de mise à jour, mais les flux ne sont malgré tout pas rechargé.
Rien n'apparait dans les logs, je vais voir si je peux les rendre plus verbeux.

**Comment by remrem** [comment]
En fait je ne pense pas que ce soit le cron qui pose problème (serveur > wget), mais plus au niveau que BT, tu peux essayer de lancer le cron manuellement depuis ton navigateur ?

**Comment by remrem** [comment]
Hum... pas sûr de mon coup, mais je me demande si ce n'est pas lié au fait que le cron est utilisé avec `WGET --spider` et que ton apache/php est configurer avec `ignore_user_abort` à false.

Peux tu tester cette procédure : 

1.  Dans le BT qui te sert, modifie le fichier `/admin/_rss.ajax.php`, en début de script après le `<?php`, mets dans une nouvelle ligne `ignore_user_abort(true);` genre : 
```
<?php
ignore_user_abort(true);
# *** LICENSE ***
# This file is part of BlogoText.
```
2. Depuis ton serveur/poste de travail (du moment que tu as accès à wget) essaye la commande du cron, mais sans le "quiet" et avec l'output `wget --spider -qO- https://ndd/blog/admin/_rss.ajax.php?guid=779d8473...`
3. Vérifie tes logs et que BT est mis à jour les flux.

**Comment by B4rb3rouss** [comment]
- Test en entrant l'URL directement dans un navigateur : ok
- Test après avoir fait les modifications proposées et utilisation de wget : succes :)

**Comment by remrem** [comment]
Cool ;)
Je PR les modifs

**Comment by B4rb3rouss** [comment]
Super !

**Comment by remrem** [comment]
Si tout est ok, peux-tu fermer cette issue ?

**Comment by B4rb3rouss** [comment]
yep :)
