### ISSUE TITLE
libravatar support

### ISSUE THREAD

**Issue by B4rb3rouss** [BoboTiG/blogotext#37]
blogotext currently supports gravatar.
The young [https://www.libravatar.org/](libravatar) project might be of interest for future developpement.

Regards.

**Comment by timovn** [comment]
Interesting.
I’ll see how that service grows.

Currently, the implementation of Gravatar in Blogotext used in the default theme has a local cache to avoid multiple connexion to 3rd party servers.

**Comment by B4rb3rouss** [comment]
J'ai ajouté le support de libravatar. En cas déchec, ça bascule sur gravatar.

Avant de faire un pull request, puisque je ne suis ni habitué à travailler avec github et PHP, je te laisse jeter un oeil à la branche libravatar : https://github.com/B4rb3rouss/blogotext/tree/libravatar

**Comment by BoboTiG** [comment]
Ça me paraît pas mal, tu peux faire un PR :)

**Comment by B4rb3rouss** [comment]
C'est fait
