### ISSUE TITLE
Supprimer plusieurs articles

### ISSUE THREAD

**Issue by emporeso2** [BoboTiG/blogotext#45]
Bonjour,
j'utilise votre escellent moteur de blog,j'aimerais savoir si il est possible de supprimer plusirs articles en meme temps ?

Merci pour votre outil.

**Comment by timovn** [comment]
Salut,
Il n’y a pas de fonction de ce genre pour le moment.

**Comment by emporeso2** [comment]
Merci en espérant que ça arrive un jour.
