### ISSUE TITLE
Problème avec la pagination

### ISSUE THREAD

**Issue by remrem** [BoboTiG/blogotext#79]
J'ai remarqué un problème sur la pagination des pages du blog, la dernière page propose d’accéder aux "éléments plus anciens", ce qui renvoie vers une page ne contenant aucun article ...

Pour exemple : http://couleur-science.eu?&p=27 propose l’accès à la page http://couleur-science.eu?&p=28 qui ne propose aucun article.

Désolé, pas motivé pour poster en anglais :/

**Comment by remrem** [comment]
Pull corrigé, cf. #80

**Comment by remrem** [comment]
Vu les commentaires de #80 , il faudrait faire une requêtes en prenant en compte bt_statut et bt_date (comme pour ?liste), le problème est que je ne vois pas trop comment gérer ça (cache ou compteur dans un fichier...)...

**Comment by timovn** [comment]
Je ne sais pas encore non plus.
Perso je préfère recycler les requêtes SQL au maximum, question de performances.

Le bug est bien présent, mais seulement dans 10% du temps. Il n’est pas non plus critique selon moi.

**Comment by BoboTiG** [comment]
Est-ce que le dernier commit corrige le soucis ? J'ai testé avec 120 articles (dont 28 non publiés) et la pagination semble correcte.

**Comment by remrem** [comment]
De mémoire, il ne me semble pas, @timovn avait annulé le commit.
Le problème étant que pour la génération de la pagination, il fallait faire une requête SQL pour avoir le nombre réel d'articles(...) (et il fallait que je revois les requêtes).

**Comment by BoboTiG** [comment]
Je parlais de mon dernier commit. Quand tu feras des tests, pense à mettre à jour ta branche de travail.

**Comment by remrem** [comment]
> Je parlais de mon dernier commit.¨

My bad, ça m'apprendra à lire en diagonale
Je vois ça ASAP (d'ici lundi).

**Comment by remrem** [comment]
Apparemment, le problème n'est pas réglé, sur une install fraîche de la branche dev, j'ai 9 articles dont 1 non publié et l'affichage configuré à 5 articles par pages :
"/" (5 art. affichés) > "article plus anciens" envoie sur "/?p=2" (0 art. affichés)
"/?p=2" (0 art. affichés) > "éléments plus récents" envoie sur "/?p=1" (3 art. affichés)

**Comment by remrem** [comment]
Bon ... bah ... désolé, je ne m'en sors pas avec l'application github pour pousser proprement les commits ...

**Comment by BoboTiG** [comment]
Merci @remrem, ça fonctionne nickel.
