### ISSUE TITLE
install blogotext

### ISSUE THREAD

**Issue by raymondbuis** [BoboTiG/blogotext#84]
pour commencer bravo pour le travail accompli...

voila une petite proposition de modification du code:
dans de nombreux cas au moment du transfert les fichier avec des nom en majuscule se retrouve chez l'hébergeur un fois déposé en ftp en minuscule... c'est le cas des fichier de traduction:
inc\lang\fr_FR.php qui se retrouve en fr.php au lieu de FR.php 

tout mettre en minuscule dés le départ ne serait il pas une bonne idée ?

cordialement

**Comment by B4rb3rouss** [comment]
Dans le cas où ce serait une bonne idée, voir le branche ici : https://github.com/B4rb3rouss/blogotext/tree/majuscules_issue_84

**Comment by BoboTiG** [comment]
@B4rb3rouss, tu peux envoyer ta PR :)
