### ISSUE TITLE
changement de mot de passe

### ISSUE THREAD

**Issue by raymondbuis** [BoboTiG/blogotext#85]
j'ai testé sur plusieurs hébergeur le code OVH 1&1 Amen php 5.5 et + la procédure de changement de mot de passe ne semble pas fonctionner!
seule solution trouver: renommer le fichier config\user.ini qui contient le mot de passe pour relancer la procédure de re création d'un user.ini neuf avec un nouveau mot de passe.
ATTENTION (il faut bien sauvegarder avant car la base sql lite est re crée aussi...)

salutations

**Comment by BoboTiG** [comment]
Salut @raymondbuis, merci pour le rapport. C'est corrigé :)
