### ISSUE TITLE
page statique + lien menu

### ISSUE THREAD

**Issue by graffx27** [BoboTiG/blogotext#86]
Ca serait top de pouvoir ajouter une pae statique reprenant le design de notre template par défaut.

J'ai essayé de dupliqué le page index, mais dés qu'on touche au code, page blanche.

Quelqu'un a une idée?

**Comment by B4rb3rouss** [comment]
À vrai dire, est-ce bien utile de coder une fonction spécialisée pour ça? C'est en réalité facile à faire de cette façon : 
1. Création d'un nouvel article
2. Désactiver les commentaires pour cet article
3. Éventuellement préciser une date ancienne pour ne pas rendre visible la page dans le flux RSS

Ensuite, en éditant le fichier list.html dans le thème, on peut rajouter un lien vers l'article. C'est en fait la création de ce lien qui pourrait être simplifiée.

**Comment by B4rb3rouss** [comment]
Je viens d'écrire un addon pour résoudre ce problème.
Chaque article taggé avec "_linklist" sera ajouté automatiquement à la place du texte ``{addon_linklist}`` présent dans le fichier list.html.

**Comment by BoboTiG** [comment]
Les addons se trouvent dans ce dépôt désormais : https://github.com/BoboTiG/blogotext-addons.
