### ISSUE TITLE
Statistiques de vues

### ISSUE THREAD

**Issue by B4rb3rouss** [BoboTiG/blogotext#89]
Dans la page d'accueil admin, on pourrait imaginer un autre graphique indiquant une évolution approximative du nombres de vues du site.

En soi, ça ne paraît pas impossible à réaliser, mais il me vient tout de même 2 questions : 

- Où enregistrer dans la base sqlite les vues? Ma question doit paraître bête, mais puisque c'est une table inexistante je ne veux pas tout casser. Dans la table "articles" ?
- Est-ce que ça ne risque pas de ralentir l'affichage des pages?

En attendant, ce petit truc est sympa : https://github.com/felladrin/online-visitors-counter/tree/master/ovc

**Comment by BoboTiG** [comment]
Je ne pense pas que BT doivent s'occuper des statistiques. Plus tard, il sera possible d'ajouter un module qui utilisera, lui, [Piwik](https://piwik.org/) ou d'autres scripts spécialisés. Ainsi, le nouveau graphique sera pris en charge par le module plutôt que BT. Ça permettra surtout d'avoir un vrai suivi et non 2-3 chiffres orphelins.

**Comment by B4rb3rouss** [comment]
Ça me va !
