### ISSUE TITLE
[addon] partage sur réseaux sociaux

### ISSUE THREAD

**Issue by B4rb3rouss** [BoboTiG/blogotext#93]
Je commence à bosser sur un plugin pour partage sur les réseaux sociaux. Je n'ai pas trouvé comment passer d'arguments à l'appel du plugin, donc il n'est disponible que si on affiche le post.
Niveau apparence, on peut peut-être faire mieux. Cependant, j'ai l'impression que même si on déclare un fichier style.css comme dans l'exemple de l'addon calendar, il n'est pas pris en compte. C'est pourquoi j'ai dû utiliser du css dans le html directement :/
À étudier et améliorer.

**Comment by BoboTiG** [comment]
Tu peux continuer le développement, dans une branche spécifique (;)), sur https://github.com/BoboTiG/blogotext-addons.

**Comment by B4rb3rouss** [comment]
Oui, je l'ai vu passer. Ça sera fait :)
